"""Static tool manifest for app and channel runtimes.

Keep this module free of heavyweight desktop/browser imports so packaged
bootstrap paths can read tool metadata without initializing automation stacks.
"""

AGENT_TOOLS = [
    {"type": "function", "function": {"name": "describe_screen", "description": "Use AI vision to describe the current screen state. Best for understanding UI layout. Ask a precise question about what you need verified instead of a vague screen dump whenever possible.", "parameters": {"type": "object", "properties": {"question": {"type": "string", "description": "Optional precise question about the screen, such as whether an app opened, an error dialog appeared, or which control should be used next."}}}}},
    {"type": "function", "function": {"name": "start_visual_monitor", "description": "Start a local full-screen visual monitor for long uncertain waits. It is non-blocking: continue useful work after starting it or leave it running after your turn as a cheap wait handle. Only one visual monitor can be active at a time; starting a new one replaces the old one. If it fires while you are still running, the runtime injects the event as system context on your next model turn; if you are idle, it wakes you. Screenshots are discarded and are not added to artifacts. After a wake, inspect with describe_screen before acting.", "parameters": {"type": "object", "properties": {"threshold_preset": {"type": "string", "enum": ["10%", "30%", "50%", "70%"], "description": "Fixed visible-screen change percentage required to wake the agent."}, "reason": {"type": "string", "description": "What the agent is waiting to see or what should happen while monitoring."}}, "required": ["threshold_preset", "reason"]}}},
    {"type": "function", "function": {"name": "stop_visual_monitor", "description": "Stop a visual monitor owned by this session or task. If monitor_id is omitted, all visual monitors owned by the current session/task are stopped.", "parameters": {"type": "object", "properties": {"monitor_id": {"type": "string", "description": "Optional monitor id returned by start_visual_monitor."}}}}},
    {"type": "function", "function": {"name": "ocr_screen", "description": "Read all text on screen using OCR. Best for extracting text content.", "parameters": {"type": "object", "properties": {}}}},
    {"type": "function", "function": {"name": "observe_browser", "description": "Get browser page state including title, URL, and key interactive elements. Best for structure and DOM state, not full page text extraction.", "parameters": {"type": "object", "properties": {}}}},
    {"type": "function", "function": {"name": "observe_desktop", "description": "List all open windows and their states using Pywinauto.", "parameters": {"type": "object", "properties": {}}}},
    {"type": "function", "function": {"name": "open_browser", "description": "Open the isolated browser and navigate to a URL. Use headless=true when you do not need a visible browser window, and headless=false when visible desktop verification is truly required.", "parameters": {"type": "object", "properties": {"url": {"type": "string", "description": "URL to navigate to"}, "headless": {"type": "boolean", "description": "Whether the isolated Selenium browser should run headless for this action."}}, "required": ["url"]}}},
    {"type": "function", "function": {"name": "browser_snapshot", "description": "Capture an ARIA/browser snapshot of the current page. Best for interactive structure and ref-based actions, not general page text.", "parameters": {"type": "object", "properties": {}}}},
    {"type": "function", "function": {"name": "browser_read_text", "description": "Read visible page text or a selector's text/value from the current isolated browser page. Use this for headings, static content, and exact rendered values.", "parameters": {"type": "object", "properties": {"selector": {"type": "string", "description": "Optional CSS selector to target a specific element."}, "max_chars": {"type": "integer", "description": "Maximum number of characters to return.", "default": 4000}}}}},
    {"type": "function", "function": {"name": "browser_click_ref", "description": "THE BEST WAY TO CLICK. Click a browser element by its [ref=N] ID. You MUST run observe_browser first to get the IDs, then use this.", "parameters": {"type": "object", "properties": {"ref": {"type": "integer", "description": "The reference ID from observe_browser (e.g. 5)"}}, "required": ["ref"]}}},
    {"type": "function", "function": {"name": "browser_type", "description": "Type text into the focused browser element, or into a specific ref when provided.", "parameters": {"type": "object", "properties": {"text": {"type": "string"}, "ref": {"type": "integer", "description": "Optional ARIA ref from observe_browser/browser_snapshot."}, "clear_first": {"type": "boolean", "default": False}}, "required": ["text"]}}},
    {"type": "function", "function": {"name": "browser_press_key", "description": "Press a key in the browser (enter, tab, escape, etc).", "parameters": {"type": "object", "properties": {"key": {"type": "string"}}, "required": ["key"]}}},
    {"type": "function", "function": {"name": "browser_scroll", "description": "Scroll the browser page.", "parameters": {"type": "object", "properties": {"direction": {"type": "string", "enum": ["up", "down"]}, "amount": {"type": "integer", "default": 300}}}}},
    {"type": "function", "function": {"name": "browser_screenshot", "description": "Capture a browser screenshot for proof/artifacts. When you need visual interpretation, ask a precise question about what should be visible. Do not rely on it as exact same-turn text extraction.", "parameters": {"type": "object", "properties": {"question": {"type": "string", "description": "Optional precise visual question about the current browser page, file, dialog, or error state."}}}}},
    {"type": "function", "function": {"name": "switch_tab", "description": "Switch to a browser tab by index (0-based).", "parameters": {"type": "object", "properties": {"index": {"type": "integer"}}, "required": ["index"]}}},
    {"type": "function", "function": {"name": "close_tab", "description": "Close the current browser tab.", "parameters": {"type": "object", "properties": {}}}},
    {"type": "function", "function": {"name": "go_back", "description": "Navigate back in browser history.", "parameters": {"type": "object", "properties": {}}}},
    {"type": "function", "function": {"name": "go_forward", "description": "Navigate forward in browser history.", "parameters": {"type": "object", "properties": {}}}},
    {"type": "function", "function": {"name": "open_app", "description": "Submit a Windows Run launch request for an application by name. This does not confirm success; verify the resulting window or error dialog visually before assuming the app opened.", "parameters": {"type": "object", "properties": {"app_name": {"type": "string", "description": "Name of app to open (e.g., 'notepad', 'spotify', 'chrome')"}}, "required": ["app_name"]}}},
    {"type": "function", "function": {"name": "focus_window", "description": "Bring a window to foreground by title.", "parameters": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}}},
    {"type": "function", "function": {"name": "minimize_window", "description": "Minimize a window by title.", "parameters": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}}},
    {"type": "function", "function": {"name": "maximize_window", "description": "Maximize a window by title.", "parameters": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}}},
    {"type": "function", "function": {"name": "close_window", "description": "Close a window by title.", "parameters": {"type": "object", "properties": {"title": {"type": "string"}}, "required": ["title"]}}},
    {"type": "function", "function": {"name": "click", "description": "Click at screen coordinates. Choose coordinates from the best observation tool for the situation. MANDATORY: After calling this, you MUST verify the result before taking any other action.", "parameters": {"type": "object", "properties": {"x": {"type": "integer", "description": "X coordinate on screen"}, "y": {"type": "integer", "description": "Y coordinate on screen"}}, "required": ["x", "y"]}}},
    {"type": "function", "function": {"name": "right_click", "description": "Right-click at screen coordinates.", "parameters": {"type": "object", "properties": {"x": {"type": "integer"}, "y": {"type": "integer"}}, "required": ["x", "y"]}}},
    {"type": "function", "function": {"name": "double_click", "description": "Double-click at screen coordinates.", "parameters": {"type": "object", "properties": {"x": {"type": "integer"}, "y": {"type": "integer"}}, "required": ["x", "y"]}}},
    {"type": "function", "function": {"name": "type_text", "description": "Type text using keyboard. MANDATORY: After calling this, you MUST verify the text appeared correctly before taking any other action.", "parameters": {"type": "object", "properties": {"text": {"type": "string"}}, "required": ["text"]}}},
    {"type": "function", "function": {"name": "press_key", "description": "Press a single key (enter, tab, escape, f1, etc).", "parameters": {"type": "object", "properties": {"key": {"type": "string"}}, "required": ["key"]}}},
    {"type": "function", "function": {"name": "hotkey", "description": "Press a key combination (e.g., ctrl+c, alt+tab, ctrl+shift+n). MANDATORY: After calling this, you MUST verify the action worked before taking any other action.", "parameters": {"type": "object", "properties": {"keys": {"type": "string", "description": "Keys separated by + (e.g., 'ctrl+c', 'ctrl+l')"}}, "required": ["keys"]}}},
    {"type": "function", "function": {"name": "scroll", "description": "Scroll at current mouse position.", "parameters": {"type": "object", "properties": {"direction": {"type": "string", "enum": ["up", "down"]}, "amount": {"type": "integer", "default": 3}}}}},
    {"type": "function", "function": {"name": "drag_and_drop", "description": "Drag from one position to another.", "parameters": {"type": "object", "properties": {"start_x": {"type": "integer"}, "start_y": {"type": "integer"}, "end_x": {"type": "integer"}, "end_y": {"type": "integer"}}, "required": ["start_x", "start_y", "end_x", "end_y"]}}},
    {"type": "function", "function": {"name": "get_clipboard", "description": "Get current clipboard content.", "parameters": {"type": "object", "properties": {}}}},
    {"type": "function", "function": {"name": "set_clipboard", "description": "Set clipboard content.", "parameters": {"type": "object", "properties": {"text": {"type": "string"}}, "required": ["text"]}}},
    {"type": "function", "function": {"name": "wait", "description": "Wait for specified seconds.", "parameters": {"type": "object", "properties": {"seconds": {"type": "number", "default": 1}}}}},
]
