import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0b1020',
    paddingHorizontal: 16,
    paddingTop: 8,
    gap: 12,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(5, 8, 18, 0.6)',
    justifyContent: 'center',
    paddingHorizontal: 22,
  },
  modalBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  promptCard: {
    backgroundColor: '#111a31',
    borderRadius: 24,
    padding: 20,
    gap: 12,
  },
  promptTitle: {
    color: '#ffffff',
    fontSize: 20,
    fontWeight: '700',
  },
  promptText: {
    color: '#d7e3fb',
    fontSize: 15,
    lineHeight: 22,
  },
  promptActions: {
    flexDirection: 'row',
    gap: 10,
    flexWrap: 'wrap',
    paddingTop: 4,
  },
  sheetOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(5, 8, 18, 0.42)',
  },
  sheetBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  sheet: {
    backgroundColor: '#0f1730',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 10,
    maxHeight: '82%',
    gap: 12,
  },
  sheetHandle: {
    alignSelf: 'center',
    width: 44,
    height: 5,
    borderRadius: 999,
    backgroundColor: '#41547f',
  },
  sheetHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
  },
  sheetHeading: {
    flex: 1,
    gap: 4,
  },
  sheetTitle: {
    color: '#ffffff',
    fontSize: 20,
    fontWeight: '700',
  },
  sheetSubtitle: {
    color: '#92a6cd',
    fontSize: 13,
    lineHeight: 19,
  },
  sheetClose: {
    color: '#7cc7ff',
    fontWeight: '700',
    fontSize: 14,
  },
  sheetContent: {
    gap: 12,
    paddingBottom: 10,
  },
  modeTabs: {
    flexDirection: 'row',
    gap: 8,
  },
  modeTab: {
    flex: 1,
    minHeight: 40,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#15213c',
  },
  modeTabActive: {
    backgroundColor: '#2dd4bf',
  },
  modeTabText: {
    color: '#dce8ff',
    fontWeight: '800',
  },
  modeTabTextActive: {
    color: '#05131e',
  },
  identityStrip: {
    borderRadius: 10,
    backgroundColor: '#0f1b33',
    borderWidth: 1,
    borderColor: '#213457',
    paddingHorizontal: 10,
    paddingVertical: 7,
    gap: 6,
  },
  identityStripLabel: {
    color: '#73e8ff',
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  identityStripHint: {
    color: '#8fa2c8',
    fontSize: 12,
    fontWeight: '600',
  },
  identityStripList: {
    gap: 8,
    paddingRight: 4,
  },
  identityChip: {
    minWidth: 92,
    maxWidth: 160,
    borderRadius: 8,
    backgroundColor: '#0b1427',
    borderWidth: 1,
    borderColor: '#22365a',
    paddingHorizontal: 9,
    paddingVertical: 7,
  },
  identityChipActive: {
    backgroundColor: '#16475a',
    borderColor: '#2dd4bf',
  },
  identityChipName: {
    color: '#dce8ff',
    fontSize: 12,
    fontWeight: '900',
  },
  identityChipNameActive: {
    color: '#ffffff',
  },
  identityChipMeta: {
    color: '#8fa2c8',
    fontSize: 10,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  identityChipMetaActive: {
    color: '#bdfdf4',
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  topButton: {
    backgroundColor: '#182342',
    borderRadius: 12,
    width: 42,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  topButtonText: {
    color: '#dce8ff',
    fontWeight: '900',
    fontSize: 18,
  },
  topButtonBadge: {
    position: 'absolute',
    top: -6,
    right: -6,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    paddingHorizontal: 5,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f97316',
  },
  topButtonBadgeText: {
    color: '#ffffff',
    fontSize: 10,
    fontWeight: '800',
  },
  titleBlock: {
    flex: 1,
    gap: 4,
  },
  title: {
    color: '#ffffff',
    fontSize: 22,
    fontWeight: '700',
  },
  subtitle: {
    color: '#8fa2c8',
    fontSize: 13,
  },
  plusButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#182342',
    alignItems: 'center',
    justifyContent: 'center',
  },
  plusButtonText: {
    color: '#ffffff',
    fontWeight: '700',
    fontSize: 22,
  },
  messages: {
    flex: 1,
  },
  messagesContent: {
    gap: 12,
    paddingBottom: 12,
    flexGrow: 1,
  },
  emptyState: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 30,
  },
  emptyHint: {
    color: '#6f82a8',
    fontSize: 15,
    textAlign: 'center',
  },
  bubble: {
    borderRadius: 18,
    padding: 14,
    gap: 8,
  },
  userBubble: {
    backgroundColor: '#21406b',
    alignSelf: 'flex-end',
    maxWidth: '88%',
  },
  assistantBubble: {
    backgroundColor: '#172038',
    alignSelf: 'flex-start',
    maxWidth: '94%',
  },
  systemBubble: {
    backgroundColor: '#1f2941',
    alignSelf: 'center',
    maxWidth: '96%',
  },
  bubbleHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 10,
  },
  bubbleRole: {
    color: '#8ecfff',
    fontWeight: '700',
    fontSize: 12,
  },
  bubbleTime: {
    color: '#8194b9',
    fontSize: 11,
  },
  bubbleText: {
    color: '#eef4ff',
    fontSize: 15,
    lineHeight: 22,
  },
  voiceBanner: {
    backgroundColor: '#16253f',
    borderRadius: 18,
    padding: 12,
    gap: 6,
  },
  voiceBannerTitle: {
    color: '#ffffff',
    fontWeight: '700',
  },
  voiceBannerText: {
    color: '#dce8ff',
    fontSize: 14,
  },
  rowWrap: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
  },
  sheetSection: {
    gap: 10,
    borderTopWidth: 1,
    borderTopColor: '#223252',
    paddingTop: 12,
  },
  sheetSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  toolPackRow: {
    minHeight: 64,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#273553',
    backgroundColor: '#111a31',
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  toolPackRowEnabled: {
    borderColor: '#3b82f6',
    backgroundColor: '#132744',
  },
  toolPackRowLocked: {
    opacity: 0.62,
    backgroundColor: '#111827',
  },
  toolPackCopy: {
    flex: 1,
    gap: 4,
  },
  toolPackTitle: {
    color: '#f5f9ff',
    fontSize: 13,
    fontWeight: '800',
  },
  toolPackTitleLocked: {
    color: '#90a0b8',
  },
  toolPackDescription: {
    color: '#93a7c8',
    fontSize: 12,
    lineHeight: 17,
  },
  toolPackSwitch: {
    width: 42,
    height: 24,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#465674',
    backgroundColor: '#1a2438',
    padding: 2,
    justifyContent: 'center',
  },
  toolPackSwitchOn: {
    borderColor: '#62b0ff',
    backgroundColor: '#23619e',
  },
  toolPackSwitchLocked: {
    borderColor: '#374151',
    backgroundColor: '#111827',
  },
  toolPackKnob: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#8391a8',
  },
  toolPackKnobOn: {
    alignSelf: 'flex-end',
    backgroundColor: '#ffffff',
  },
  statusRowCompact: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 6,
  },
  statusRowLabel: {
    color: '#8fa2c8',
    fontSize: 13,
  },
  statusRowValue: {
    flex: 1,
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '600',
    textAlign: 'right',
  },
  helperText: {
    color: '#a9bbdf',
    fontSize: 13,
    lineHeight: 19,
  },
  screenPreview: {
    width: '100%',
    aspectRatio: 16 / 10,
    borderRadius: 14,
    backgroundColor: '#0f1730',
  },
  betaBlock: {
    gap: 8,
  },
  quickControlBlock: {
    gap: 8,
  },
  quickControlLabel: {
    color: '#dce8ff',
    fontSize: 13,
    fontWeight: '700',
  },
  workspaceInput: {
    flex: 1,
    minWidth: 180,
    backgroundColor: '#0f1730',
    color: '#ffffff',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  workspaceInputCompact: {
    minWidth: 110,
    backgroundColor: '#0f1730',
    color: '#ffffff',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  textAreaInput: {
    minHeight: 92,
    backgroundColor: '#0f1730',
    color: '#ffffff',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    textAlignVertical: 'top',
  },
  infoCard: {
    backgroundColor: '#101933',
    borderRadius: 14,
    padding: 12,
    gap: 4,
  },
  activeInfoCard: {
    borderWidth: 1,
    borderColor: '#5f8fff',
  },
  infoCardLabel: {
    color: '#dce8ff',
    fontSize: 12,
    fontWeight: '700',
  },
  infoCardText: {
    color: '#d8e5fb',
    fontSize: 12,
    lineHeight: 18,
  },
  artifactImage: {
    width: '100%',
    aspectRatio: 4 / 3,
    borderRadius: 12,
    backgroundColor: '#0f1730',
    marginTop: 8,
  },
  artifactTextBox: {
    maxHeight: 260,
    borderRadius: 12,
    backgroundColor: '#0f1730',
    marginTop: 8,
    padding: 10,
  },
  artifactText: {
    color: '#d8e5fb',
    fontSize: 12,
    lineHeight: 18,
  },
  logLine: {
    color: '#d8e5fb',
    fontSize: 12,
    lineHeight: 18,
  },
  composerShell: {
    backgroundColor: '#10192e',
    borderRadius: 20,
    padding: 12,
    gap: 10,
    marginBottom: 8,
  },
  composerActionRow: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
    alignItems: 'center',
  },
  composerChip: {
    minHeight: 34,
    maxWidth: 170,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: '#26395d',
    backgroundColor: '#121d36',
    paddingHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  composerChipActive: {
    borderColor: '#2dd4bf',
    backgroundColor: '#143544',
  },
  composerChipText: {
    color: '#dce8ff',
    fontSize: 12,
    fontWeight: '800',
  },
  composerChipTextActive: {
    color: '#ffffff',
  },
  composerMenuPanel: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#26395d',
    backgroundColor: '#0b1427',
    padding: 10,
    gap: 10,
  },
  composerMenuLabel: {
    color: '#8fa2c8',
    fontSize: 11,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  composerMenuButton: {
    minHeight: 34,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#26395d',
    backgroundColor: '#121d36',
    paddingHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  composerMenuButtonActive: {
    borderColor: '#2dd4bf',
    backgroundColor: '#2dd4bf',
  },
  composerMenuButtonText: {
    color: '#dce8ff',
    fontSize: 12,
    fontWeight: '800',
  },
  composerMenuButtonTextActive: {
    color: '#04111d',
  },
  plusButtonSmall: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#182342',
    alignItems: 'center',
    justifyContent: 'center',
  },
  plusButtonSmallText: {
    color: '#ffffff',
    fontSize: 20,
    fontWeight: '700',
  },
  voiceStartButton: {
    backgroundColor: '#0f8f62',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  voiceStopButton: {
    backgroundColor: '#b45309',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  voiceCancelButton: {
    backgroundColor: '#6a2630',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  voiceButtonText: {
    color: '#ffffff',
    fontWeight: '700',
    fontSize: 13,
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 10,
  },
  input: {
    flex: 1,
    backgroundColor: '#141c33',
    color: '#ffffff',
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 12,
    minHeight: 50,
    maxHeight: 110,
  },
  lockedInput: {
    justifyContent: 'center',
  },
  lockedInputText: {
    color: '#8ea2cb',
    fontSize: 15,
  },
  sendButton: {
    backgroundColor: '#3b82f6',
    borderRadius: 16,
    paddingHorizontal: 18,
    paddingVertical: 14,
  },
  sendButtonDisabled: {
    opacity: 0.45,
  },
  sendButtonText: {
    color: '#ffffff',
    fontWeight: '700',
  },
  primaryButton: {
    backgroundColor: '#3b82f6',
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  primaryButtonText: {
    color: '#ffffff',
    fontWeight: '700',
  },
  secondaryButton: {
    backgroundColor: '#223153',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  secondaryButtonText: {
    color: '#ffffff',
    fontWeight: '700',
    fontSize: 13,
  },
  activeSecondary: {
    backgroundColor: '#3b82f6',
  },
  liveButton: {
    backgroundColor: '#0f8f62',
  },
  disabledButton: {
    opacity: 0.55,
  },
});
