import { Platform, StyleSheet } from 'react-native';

import { DESKTOP_UI as UI } from './desktopUiTokens';

const WEB_FONT = Platform.OS === 'web' ? UI.type.sans : undefined;
const WEB_MONO = Platform.OS === 'web' ? UI.type.mono : undefined;

export const automationStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: UI.color.canvas,
    fontFamily: WEB_FONT,
    overflow: 'hidden',
    ...(Platform.OS === 'web' ? { height: '100vh' as any, maxHeight: '100vh' as any } : {}),
  },
  page: { flex: 1, padding: 18, gap: 14, minHeight: 0, overflow: 'hidden' },
  headerActions: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  liveStatus: { color: UI.color.textSubtle, fontSize: 12, maxWidth: 220 },
  button: {
    minHeight: 44,
    borderRadius: UI.radius.control,
    paddingHorizontal: 14,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: UI.color.borderStrong,
    backgroundColor: UI.color.surfaceMuted,
  },
  buttonHover: { borderColor: UI.color.accentBorder, backgroundColor: UI.color.surfaceHover },
  buttonPressed: { opacity: 0.82 },
  buttonFocus: { borderColor: UI.color.accent, borderWidth: 2 },
  primaryButton: { backgroundColor: UI.color.accent, borderColor: UI.color.accent },
  buttonText: { color: UI.color.text, fontSize: 12, fontWeight: '700' },
  primaryButtonText: { color: UI.color.accentInk },
  dangerButton: { backgroundColor: UI.color.dangerSoft, borderColor: 'rgba(224,120,132,0.38)' },
  dangerText: { color: '#f3b5bd' },
  disabled: { opacity: 0.45 },

  workspace: {
    flex: 1,
    minHeight: 0,
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: UI.color.border,
    borderRadius: UI.radius.panel,
    overflow: 'hidden',
    backgroundColor: UI.color.surfaceMuted,
  },
  listPane: { width: 352, minWidth: 290, minHeight: 0, backgroundColor: UI.color.sidebar, borderRightWidth: 1, borderRightColor: UI.color.border },
  listHeader: { padding: 14, gap: 12, borderBottomWidth: 1, borderBottomColor: UI.color.border },
  listTitleRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  sectionTitle: { color: UI.color.text, fontSize: 14, fontWeight: '700' },
  sectionMeta: { color: UI.color.textSubtle, fontSize: 12 },
  searchInput: {
    minHeight: 44,
    borderRadius: UI.radius.control,
    borderWidth: 1,
    borderColor: UI.color.borderStrong,
    backgroundColor: UI.color.canvas,
    color: UI.color.text,
    paddingHorizontal: 12,
    fontSize: 13,
  },
  filterRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  filterButton: {
    minHeight: 36,
    borderRadius: UI.radius.pill,
    borderWidth: 1,
    borderColor: UI.color.border,
    paddingHorizontal: 11,
    alignItems: 'center',
    justifyContent: 'center',
  },
  filterButtonActive: { borderColor: UI.color.accentBorder, backgroundColor: UI.color.accentSoft },
  filterText: { color: UI.color.textMuted, fontSize: 11, fontWeight: '700' },
  filterTextActive: { color: UI.color.accentStrong },
  listContent: { padding: 8, gap: 4 },
  jobRow: { minHeight: 102, padding: 12, borderRadius: UI.radius.control, borderWidth: 1, borderColor: 'transparent', gap: 7 },
  jobRowHover: { backgroundColor: UI.color.surfaceHover },
  jobRowSelected: { backgroundColor: UI.color.accentSoft, borderColor: UI.color.accentBorder },
  jobTopRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  jobName: { flex: 1, minWidth: 0, color: UI.color.text, fontSize: 14, fontWeight: '700' },
  statusBadge: { borderRadius: UI.radius.small, paddingHorizontal: 7, paddingVertical: 3, backgroundColor: UI.color.successSoft },
  statusBadgePaused: { backgroundColor: UI.color.surfaceRaised },
  statusBadgeAttention: { backgroundColor: UI.color.warningSoft },
  statusBadgeText: { color: UI.color.success, fontSize: 10, fontWeight: '700' },
  statusBadgeTextPaused: { color: UI.color.textMuted },
  statusBadgeTextAttention: { color: UI.color.warning },
  jobSchedule: { color: UI.color.accentStrong, fontFamily: WEB_MONO, fontSize: 11 },
  jobPrompt: { color: UI.color.textMuted, fontSize: 12, lineHeight: 17 },
  listEmpty: { flex: 1, padding: 24, alignItems: 'center', justifyContent: 'center', gap: 8 },
  emptyTitle: { color: UI.color.text, fontSize: 16, fontWeight: '700', textAlign: 'center' },
  emptyCopy: { color: UI.color.textMuted, fontSize: 12, lineHeight: 18, textAlign: 'center', maxWidth: 360 },

  mainPane: { flex: 1, minWidth: 0, minHeight: 0, overflow: 'hidden', backgroundColor: UI.color.canvas },
  detailScroll: { flex: 1, minHeight: 0 },
  detailContent: { padding: 22, gap: 18, paddingBottom: 42 },
  detailHeader: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 18 },
  detailHeaderCopy: { flex: 1, minWidth: 0, gap: 5 },
  eyebrow: { color: UI.color.accentStrong, fontSize: 11, fontWeight: '700', letterSpacing: 0.6, textTransform: 'uppercase' },
  detailTitle: { color: UI.color.text, fontSize: 26, lineHeight: 32, fontWeight: '700', letterSpacing: -0.5 },
  detailSubtitle: { color: UI.color.textMuted, fontSize: 13, lineHeight: 19 },
  detailActions: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'flex-end', gap: 8, maxWidth: 430 },
  tabRow: { flexDirection: 'row', gap: 4, borderBottomWidth: 1, borderBottomColor: UI.color.border },
  tab: { minHeight: 42, paddingHorizontal: 13, justifyContent: 'center', borderBottomWidth: 2, borderBottomColor: 'transparent' },
  tabActive: { borderBottomColor: UI.color.accent },
  tabText: { color: UI.color.textMuted, fontSize: 12, fontWeight: '700' },
  tabTextActive: { color: UI.color.text },

  runway: {
    minHeight: 150,
    borderRadius: UI.radius.large,
    borderWidth: 1,
    borderColor: UI.color.accentBorder,
    backgroundColor: '#0b151c',
    padding: 18,
    overflow: 'hidden',
  },
  runwayGlow: {
    position: 'absolute', right: -60, top: -85, width: 260, height: 260, borderRadius: 999,
    backgroundColor: 'rgba(92,200,215,0.08)',
  },
  runwayKicker: { color: UI.color.textSubtle, fontSize: 11, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.6 },
  runwayTime: { color: UI.color.text, fontSize: 23, fontWeight: '700', marginTop: 10 },
  runwaySchedule: { color: UI.color.accentStrong, fontFamily: WEB_MONO, fontSize: 12, marginTop: 7 },
  runwayLine: { height: 1, backgroundColor: UI.color.accentBorder, marginTop: 20 },
  runwayMarkers: { flexDirection: 'row', justifyContent: 'space-between', marginTop: -5 },
  runwayMarker: { width: 9, height: 9, borderRadius: 99, backgroundColor: UI.color.accent },
  runwayMarkerMuted: { backgroundColor: UI.color.borderStrong },
  runwayMeta: { color: UI.color.textSubtle, fontSize: 11, marginTop: 10 },

  contentGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  infoBlock: { flexGrow: 1, flexBasis: 230, minWidth: 0, paddingVertical: 12, borderTopWidth: 1, borderTopColor: UI.color.border, gap: 5 },
  infoBlockWide: { flexBasis: '100%' },
  infoLabel: { color: UI.color.textSubtle, fontSize: 10, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.5 },
  infoValue: { color: UI.color.textMuted, fontSize: 13, lineHeight: 19 },
  statsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 1, borderRadius: UI.radius.panel, overflow: 'hidden', backgroundColor: UI.color.border },
  stat: { flex: 1, minWidth: 130, backgroundColor: UI.color.surface, padding: 14, gap: 4 },
  statValue: { color: UI.color.text, fontSize: 22, fontWeight: '700', fontVariant: ['tabular-nums'] },
  statLabel: { color: UI.color.textSubtle, fontSize: 11 },

  section: { gap: 10 },
  sectionHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  activityRow: { paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: UI.color.border, gap: 6 },
  activityTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  activityTitle: { flex: 1, color: UI.color.text, fontSize: 13, fontWeight: '700' },
  activityMeta: { color: UI.color.textSubtle, fontSize: 11 },
  activityCopy: { color: UI.color.textMuted, fontSize: 13, lineHeight: 19 },
  inlineActions: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  textAction: { minHeight: 36, justifyContent: 'center', paddingHorizontal: 2 },
  textActionText: { color: UI.color.accentStrong, fontSize: 12, fontWeight: '700' },
  textActionDanger: { color: UI.color.danger },
  warningPanel: { borderRadius: UI.radius.control, padding: 12, backgroundColor: UI.color.warningSoft, borderWidth: 1, borderColor: 'rgba(215,174,106,0.3)', gap: 4 },
  warningTitle: { color: UI.color.warning, fontSize: 12, fontWeight: '700' },
  warningCopy: { color: '#cab891', fontSize: 12, lineHeight: 18 },
  codeText: { color: UI.color.textMuted, fontFamily: WEB_MONO, fontSize: 11, lineHeight: 17 },

  heroEmpty: { flex: 1, padding: 42, justifyContent: 'center', alignItems: 'center' },
  heroInner: { width: '100%', maxWidth: 760, gap: 18 },
  heroEyebrow: { color: UI.color.accentStrong, fontFamily: WEB_MONO, fontSize: 11, letterSpacing: 1 },
  heroTitle: { color: UI.color.text, fontSize: 34, lineHeight: 40, fontWeight: '700', letterSpacing: -0.8, maxWidth: 650 },
  heroCopy: { color: UI.color.textMuted, fontSize: 14, lineHeight: 22, maxWidth: 610 },
  templateGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginTop: 8 },
  template: { flexGrow: 1, flexBasis: 190, minHeight: 118, borderRadius: UI.radius.panel, borderWidth: 1, borderColor: UI.color.border, backgroundColor: UI.color.surfaceMuted, padding: 14, gap: 7 },
  templateHover: { borderColor: UI.color.accentBorder, backgroundColor: UI.color.surfaceHover },
  templateTitle: { color: UI.color.text, fontSize: 14, fontWeight: '700' },
  templateCopy: { color: UI.color.textMuted, fontSize: 12, lineHeight: 17 },
  templateSchedule: { color: UI.color.accentStrong, fontFamily: WEB_MONO, fontSize: 10, marginTop: 'auto' },

  editor: { flex: 1, minWidth: 0, minHeight: 0, overflow: 'hidden' },
  editorHeader: { padding: 20, borderBottomWidth: 1, borderBottomColor: UI.color.border, gap: 6 },
  editorBody: { padding: 20, gap: 22, paddingBottom: 48 },
  editorSection: { gap: 11 },
  editorSectionTitle: { color: UI.color.text, fontSize: 15, fontWeight: '700' },
  editorSectionCopy: { color: UI.color.textSubtle, fontSize: 12, lineHeight: 18 },
  field: { gap: 7 },
  fieldRow: { flexDirection: 'row', gap: 10, flexWrap: 'wrap' },
  fieldHalf: { flex: 1, minWidth: 220, gap: 7 },
  fieldLabel: { color: UI.color.textMuted, fontSize: 12, fontWeight: '700' },
  required: { color: UI.color.accentStrong },
  input: { minHeight: 44, borderRadius: UI.radius.control, borderWidth: 1, borderColor: UI.color.borderStrong, backgroundColor: UI.color.surfaceMuted, color: UI.color.text, paddingHorizontal: 12, paddingVertical: 10, fontSize: 13 },
  inputError: { borderColor: UI.color.danger },
  textArea: { minHeight: 104, textAlignVertical: 'top' },
  fieldError: { color: UI.color.danger, fontSize: 11, lineHeight: 16 },
  choiceRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  choice: { minHeight: 44, borderRadius: UI.radius.control, borderWidth: 1, borderColor: UI.color.border, paddingHorizontal: 12, justifyContent: 'center', backgroundColor: UI.color.surfaceMuted },
  choiceSelected: { borderColor: UI.color.accentBorder, backgroundColor: UI.color.accentSoft },
  choiceText: { color: UI.color.textMuted, fontSize: 12, fontWeight: '700' },
  choiceTextSelected: { color: UI.color.accentStrong },
  optionStack: { gap: 8 },
  optionCard: { minHeight: 62, borderRadius: UI.radius.control, borderWidth: 1, borderColor: UI.color.border, padding: 11, backgroundColor: UI.color.surfaceMuted, gap: 4 },
  optionCardSelected: { borderColor: UI.color.accentBorder, backgroundColor: UI.color.accentSoft },
  optionTitle: { color: UI.color.text, fontSize: 12, fontWeight: '700' },
  optionCopy: { color: UI.color.textSubtle, fontSize: 11, lineHeight: 16 },
  reviewStrip: { borderRadius: UI.radius.panel, borderWidth: 1, borderColor: UI.color.accentBorder, backgroundColor: '#0b151c', padding: 14, gap: 7 },
  reviewTitle: { color: UI.color.text, fontSize: 13, fontWeight: '700' },
  reviewCopy: { color: UI.color.textMuted, fontSize: 12, lineHeight: 18 },
  editorFooter: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12, flexWrap: 'wrap' },
  editorFooterActions: { flexDirection: 'row', gap: 8, marginLeft: 'auto' },
});
