import { Platform, StyleSheet } from 'react-native';

import { DESKTOP_RECT_BUTTON_RADIUS } from './desktopUiTokens';
import { COMPOSER_LINE_HEIGHT, COMPOSER_MAX_HEIGHT, COMPOSER_MIN_HEIGHT, HUD } from './DesktopConversationView.styleConstants';

const SIDEBAR_ICON_STYLE = Platform.OS === 'web'
  ? ({
      fontFamily: 'Segoe UI Symbol, Segoe UI, sans-serif',
      fontVariant: ['tabular-nums'],
    } as any)
  : null;

export const desktopConversationStylesPart1 = StyleSheet.create({
  monoIconBase: {
    color: '#dfe8f5',
    fontSize: 14,
    fontWeight: '500',
    textAlign: 'center',
  },
  shell: {
    flex: 1,
    flexDirection: 'row',
    gap: 0,
    alignItems: 'stretch',
    position: 'relative',
    backgroundColor: '#050b14',
  },
  sidebarDock: {
    ...(Platform.OS === 'web' ? ({ order: -1 } as any) : null),
    flexShrink: 0,
    alignItems: 'stretch',
    backgroundColor: '#06101f',
    borderRadius: 0,
    borderWidth: 1,
    borderColor: 'rgba(24, 243, 255, 0.14)',
    overflow: 'hidden',
    position: 'relative',
  },
  sidebarDockCollapsed: {
    width: 0,
    borderWidth: 0,
    backgroundColor: 'transparent',
  },
  sidebarDockExpanded: {
    width: 328,
    maxWidth: 560,
    flexDirection: 'row',
  },
  sidebarDockBody: {
    flex: 1,
    minWidth: 0,
  },
  sidebarDockResizeHandle: {
    position: 'absolute',
    right: 0,
    top: 0,
    bottom: 0,
    width: 10,
    zIndex: 5,
    alignItems: 'center',
    justifyContent: 'center',
    ...(Platform.OS === 'web' ? ({ cursor: 'col-resize' } as any) : null),
  },
  sidebarCollapsedHandle: {
    position: 'absolute',
    top: 8,
    right: 0,
    width: 18,
    height: 40,
    borderTopLeftRadius: 10,
    borderBottomLeftRadius: 10,
    backgroundColor: 'rgba(7, 19, 34, 0.72)',
    borderWidth: 1,
    borderRightWidth: 0,
    borderColor: 'rgba(24, 243, 255, 0.18)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sidebarCollapsedHandleHovered: {
    backgroundColor: '#082235',
    borderColor: HUD.cyanDim,
  },
  sidebarCollapsedHandleGlyph: {
    color: '#dff8ff',
    fontSize: 22,
    lineHeight: 24,
    fontWeight: '900',
  },
  sidebarHeaderCollapseButton: {
    position: 'absolute',
    top: 8,
    left: 8,
    width: 40,
    height: 40,
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: '#071525',
    borderWidth: 1,
    borderColor: 'rgba(24, 243, 255, 0.16)',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10,
  },
  sidebarHeaderCollapseButtonHovered: {
    backgroundColor: '#082235',
    borderColor: HUD.cyanDim,
  },
  sidebarHeaderCollapseGlyph: {
    color: '#e9fbff',
    fontSize: 25,
    lineHeight: 27,
    fontWeight: '900',
  },
  utilityRail: {
    width: '100%',
    paddingVertical: 14,
    paddingHorizontal: 8,
    gap: 10,
    alignItems: 'center',
  },
  utilityRailExpanded: {
    width: 70,
    flexShrink: 0,
    borderRightWidth: 1,
    borderRightColor: 'rgba(24, 243, 255, 0.12)',
    alignItems: 'stretch',
    justifyContent: 'flex-start',
  },
  utilityRailButton: {
    width: 52,
    height: 52,
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: 'transparent',
    paddingVertical: 0,
    paddingHorizontal: 0,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
  },
  utilityRailButtonHovered: {
    backgroundColor: '#071b2b',
    borderColor: HUD.cyanDim,
  },
  utilityRailButtonPressed: {
    transform: [{ scale: 0.96 }],
  },
  utilityRailButtonActive: {
    backgroundColor: 'transparent',
    borderColor: 'transparent',
  },
  utilityRailIcon: {
    color: '#f7fbff',
    fontSize: 19,
    fontWeight: '500',
  },
  utilityRailCollapseGlyph: {
    color: '#f7fbff',
    fontSize: 28,
    lineHeight: 30,
    fontWeight: '900',
  },
  utilityRailLabel: {
    color: '#9ab3d7',
    fontSize: 10,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  utilityRailLabelActive: {
    color: '#f7fbff',
  },
  utilityRailDivider: {
    width: '100%',
    height: 1,
    backgroundColor: 'rgba(24, 243, 255, 0.12)',
    marginVertical: 2,
  },
  utilityRailTab: {
    width: '100%',
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: '#071525',
    borderWidth: 1,
    borderColor: 'rgba(24, 243, 255, 0.12)',
    paddingVertical: 10,
    paddingHorizontal: 8,
    alignItems: 'center',
    gap: 4,
  },
  utilityRailTabExpanded: {
    minHeight: 52,
    alignItems: 'flex-start',
    paddingHorizontal: 12,
  },
  utilityRailTabActive: {
    backgroundColor: '#082234',
    borderColor: HUD.cyan,
  },
  utilityRailTabDisabled: {
    opacity: 0.62,
  },
  utilityRailTabLabel: {
    color: '#d7e7ff',
    fontSize: 10,
    fontWeight: '800',
    textAlign: 'center',
  },
  utilityRailTabLabelExpanded: {
    width: '100%',
    fontSize: 12,
    textAlign: 'left',
  },
  utilityRailTabLabelActive: {
    color: '#f7fbff',
  },
  utilityRailTabMeta: {
    color: '#7f97bc',
    fontSize: 9,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    textAlign: 'center',
  },
  utilityRailTabMetaExpanded: {
    textAlign: 'left',
  },
  utilityRailTabMetaActive: {
    color: HUD.cyan,
  },
  sessionsRail: {
    width: 280,
    borderRadius: 16,
    backgroundColor: '#071322',
    borderWidth: 1,
    borderColor: 'rgba(24, 243, 255, 0.16)',
    padding: 18,
    gap: 14,
  },
  railHeader: {
    gap: 14,
  },
  railTitleBlock: {
    gap: 6,
  },
  railHeaderActions: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
  },
  eyebrow: {
    color: '#7ea3d8',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1.1,
    textTransform: 'uppercase',
  },
  railTitle: {
    color: '#f7fbff',
    fontSize: 26,
    fontWeight: '800',
  },
  railText: {
    color: '#98accd',
    fontSize: 13,
    lineHeight: 19,
  },
  primaryRailButton: {
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: '#d4ff65',
    paddingVertical: 12,
    paddingHorizontal: 14,
    alignItems: 'center',
  },
  primaryRailButtonText: {
    color: '#0b1325',
    fontWeight: '800',
  },
  secondaryRailButton: {
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: '#17253f',
    paddingVertical: 12,
    paddingHorizontal: 14,
    alignItems: 'center',
  },
  secondaryRailButtonText: {
    color: '#dbe7fb',
    fontWeight: '800',
  },
  railMetaRow: {
    flexDirection: 'row',
    gap: 10,
  },
  railMetaCard: {
    flex: 1,
    borderRadius: 16,
    backgroundColor: '#121f39',
    padding: 12,
    gap: 4,
  },
  metaLabel: {
    color: '#8397ba',
    fontSize: 11,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  metaValue: {
    color: '#eef5ff',
    fontWeight: '700',
  },
  sidebarContentStack: {
    gap: 8,
    paddingHorizontal: 8,
    paddingTop: 34,
    paddingBottom: 12,
  },
  sidebarAccountFooter: {
    position: 'relative',
    zIndex: 20,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.10)',
    backgroundColor: '#101010',
    paddingHorizontal: 8,
    paddingVertical: 8,
  },
  sidebarAccountButton: {
    minHeight: 48,
    borderRadius: 6,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 8,
    paddingVertical: 7,
  },
  sidebarAccountButtonHovered: {
    backgroundColor: '#1b1b1b',
  },
  sidebarAccountButtonPressed: {
    backgroundColor: '#242424',
  },
  sidebarAccountButtonActive: {
    backgroundColor: '#202020',
  },
  sidebarAccountAvatar: {
    width: 30,
    height: 30,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#9b55c7',
  },
  sidebarAccountAvatarText: {
    color: '#ffffff',
    fontSize: 11,
    fontWeight: '800',
  },
  sidebarAccountCopy: {
    flex: 1,
    minWidth: 0,
  },
  sidebarAccountEmail: {
    color: '#f3f3f3',
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
  },
  sidebarAccountUpdateBadge: {
    minHeight: 24,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#3b9dff',
    paddingHorizontal: 11,
  },
  sidebarAccountUpdateText: {
    color: '#ffffff',
    fontSize: 10,
    lineHeight: 12,
    fontWeight: '900',
  },
  sidebarAccountMenu: {
    position: 'absolute',
    left: 8,
    right: 8,
    bottom: 62,
    zIndex: 30,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    backgroundColor: '#151515',
    paddingVertical: 6,
    overflow: 'hidden',
    ...(Platform.OS === 'web'
      ? ({
          boxShadow: '0 16px 36px rgba(0, 0, 0, 0.38)',
        } as any)
      : null),
  },
  sidebarAccountMenuRow: {
    minHeight: 34,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  sidebarAccountMenuRowHovered: {
    backgroundColor: '#222222',
  },
  sidebarAccountMenuRowPressed: {
    backgroundColor: '#2b2b2b',
  },
  sidebarAccountMenuDangerRow: {
    marginTop: 4,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.08)',
  },
  sidebarAccountMenuDangerRowHovered: {
    backgroundColor: 'rgba(255, 87, 87, 0.12)',
  },
  sidebarAccountMenuRowDisabled: {
    opacity: 0.55,
  },
  sidebarAccountMenuIcon: {
    color: '#cfcfcf',
    fontSize: 13,
    lineHeight: 16,
    width: 18,
    textAlign: 'center',
    ...(SIDEBAR_ICON_STYLE as any),
  },
  sidebarAccountMenuText: {
    flex: 1,
    color: '#f3f3f3',
    fontSize: 12,
    fontWeight: '700',
  },
  sidebarNavStack: {
    gap: 3,
  },
  sidebarListRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 7,
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    minHeight: 28,
    paddingHorizontal: 6,
    paddingVertical: 4,
  },
  sidebarListRowIcon: {
    color: '#dfe8f5',
    fontSize: 13,
    lineHeight: 16,
    width: 18,
    textAlign: 'center',
    ...(SIDEBAR_ICON_STYLE as any),
  },
  sidebarListRowCopy: {
    flex: 1,
    gap: 1,
  },
  sidebarListRowTitle: {
    color: '#f4f8ff',
    fontSize: 12,
    fontWeight: '700',
    flex: 1,
  },
  sidebarListRowText: {
    color: '#8f8f8f',
    fontSize: 11,
    lineHeight: 15,
  },
  sidebarListRowMeta: {
    color: '#8f8f8f',
    fontSize: 9,
    fontWeight: '700',
    flexShrink: 1,
  },
  sidebarSearchShell: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: '#2a2a2a',
    minHeight: 34,
    paddingHorizontal: 9,
    paddingVertical: 7,
  },
  sidebarSearchGlyph: {
    color: '#9a9a9a',
    fontSize: 13,
    lineHeight: 16,
    width: 18,
    textAlign: 'center',
    ...(SIDEBAR_ICON_STYLE as any),
  },
  sidebarSearchButtonText: {
    color: '#dfe8f5',
    fontSize: 12,
    fontWeight: '600',
    flex: 1,
  },
  sidebarComputerTabsRow: {
    flexDirection: 'row',
    gap: 6,
  },
  sidebarComputerTab: {
    flex: 1,
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: '#242424',
    minHeight: 30,
    paddingHorizontal: 9,
    paddingVertical: 6,
    alignItems: 'center',
  },
  sidebarComputerTabActive: {
    backgroundColor: '#323232',
  },
  sidebarComputerTabDisabled: {
    opacity: 0.6,
  },
  sidebarComputerTabText: {
    color: '#a2a2a2',
    fontSize: 11,
    fontWeight: '700',
  },
  sidebarComputerTabTextActive: {
    color: '#f4f8ff',
  },
  fleetWorkspace: {
    flex: 1,
    maxWidth: 1280,
    flexDirection: 'row',
    gap: 0,
    minHeight: 0,
  },
  fleetManagerChatPanel: {
    width: 340,
    minWidth: 310,
    flexShrink: 0,
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: '#071322',
    borderWidth: 1,
    borderColor: 'rgba(24, 243, 255, 0.18)',
    overflow: 'hidden',
  },
  verticalPanelResizeHandle: {
    width: 10,
    flexShrink: 0,
    alignSelf: 'stretch',
    alignItems: 'center',
    justifyContent: 'center',
    ...(Platform.OS === 'web' ? ({ cursor: 'col-resize' } as any) : null),
  },
  panelResizeHandleHovered: {
    backgroundColor: 'transparent',
  },
  panelResizeGrip: {
    width: 18,
    height: 18,
    minHeight: 18,
    borderRadius: 999,
    borderWidth: 0,
    borderColor: 'transparent',
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
    opacity: 0,
  },
  panelResizeGripVisible: {
    opacity: 1,
  },
  panelResizeGripText: {
    color: 'rgba(223, 248, 255, 0.74)',
    fontSize: 15,
    lineHeight: 16,
    fontWeight: '900',
  },
  fleetCollapsedRail: {
    width: 54,
    flexShrink: 0,
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: '#071322',
    borderWidth: 1,
    borderColor: 'rgba(24, 243, 255, 0.18)',
    alignItems: 'center',
    paddingVertical: 10,
    gap: 10,
    marginLeft: 14,
  },
  fleetCollapsedRailText: {
    color: '#8fa4c4',
    fontSize: 10,
    fontWeight: '900',
    textTransform: 'uppercase',
    transform: [{ rotate: '-90deg' }],
    marginTop: 18,
  },
  fleetChatIdentitySelector: {
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(24, 243, 255, 0.12)',
    paddingHorizontal: 12,
    paddingTop: 12,
    paddingBottom: 10,
    gap: 8,
  },
  fleetChatIdentityHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  fleetChatIdentityHeader: {
    flex: 1,
    gap: 3,
  },
  fleetChatIdentityHint: {
    color: '#8fa4c4',
    fontSize: 10,
    fontWeight: '700',
  },
  fleetChatIdentityList: {
    gap: 7,
    paddingRight: 4,
  },
  fleetChatIdentityScroll: {
    maxHeight: 54,
  },
  fleetChatIdentityChip: {
    width: 128,
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: '#06111f',
    borderWidth: 1,
    borderColor: 'rgba(24, 243, 255, 0.14)',
    paddingHorizontal: 9,
    paddingVertical: 8,
    gap: 2,
  },
  fleetChatIdentityChipActive: {
    backgroundColor: '#12384a',
    borderColor: 'rgba(24, 243, 255, 0.55)',
  },
  fleetChatIdentityName: {
    color: '#dfefff',
    fontSize: 11,
    fontWeight: '900',
  },
  fleetChatIdentityNameActive: {
    color: '#ffffff',
  },
  fleetChatIdentityMeta: {
    color: '#7f95ba',
    fontSize: 9,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  fleetChatIdentityMetaActive: {
    color: HUD.cyanSoft,
  },
  fleetChatIdentityEmpty: {
    color: '#8fa4c4',
    fontSize: 11,
    lineHeight: 16,
  },
  fleetManagerChatHeader: {
    paddingHorizontal: 12,
    paddingTop: 12,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(24, 243, 255, 0.12)',
    gap: 5,
  },
  fleetManagerChatTitle: {
    color: '#f6fbff',
    fontSize: 17,
    fontWeight: '900',
  },
  fleetManagerChatMetaRow: {
    flexDirection: 'row',
    gap: 7,
    flexWrap: 'wrap',
  },
  fleetManagerChatMeta: {
    color: '#9bb3d4',
    fontSize: 10,
    fontWeight: '800',
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: '#0a1b2d',
    borderWidth: 1,
    borderColor: 'rgba(24, 243, 255, 0.12)',
    paddingHorizontal: 7,
    paddingVertical: 4,
  },
  fleetManagerTranscript: {
    flex: 1,
    minHeight: 0,
  },
  fleetManagerTranscriptContent: {
    padding: 10,
    gap: 9,
  },
  fleetManagerEmptyChat: {
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    borderWidth: 1,
    borderColor: 'rgba(24, 243, 255, 0.14)',
    backgroundColor: '#06111f',
    padding: 10,
    gap: 4,
  },
  fleetManagerEmptyTitle: {
    color: '#f1f7ff',
    fontSize: 13,
    fontWeight: '900',
  },
  fleetManagerEmptyText: {
    color: '#8fa4c4',
    fontSize: 11,
    lineHeight: 16,
  },
  fleetManagerMessage: {
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    paddingHorizontal: 10,
    paddingVertical: 9,
    gap: 6,
  },
  fleetManagerMessageUser: {
    alignSelf: 'flex-end',
    maxWidth: '88%',
    backgroundColor: '#d4ff65',
  },
  fleetManagerMessageAssistant: {
    alignSelf: 'stretch',
    backgroundColor: '#06111f',
    borderWidth: 1,
    borderColor: 'rgba(24, 243, 255, 0.1)',
  },
  fleetManagerMessageSystem: {
    alignSelf: 'stretch',
    backgroundColor: '#231936',
    borderWidth: 1,
    borderColor: 'rgba(154, 111, 255, 0.24)',
  },
  fleetManagerMessageHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 8,
  },
  fleetManagerMessageLabel: {
    color: '#7d94bf',
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 0.7,
    textTransform: 'uppercase',
  },
  fleetManagerMessageLabelOnLight: {
    color: '#163017',
  },
  fleetManagerMessageTime: {
    color: '#7d94bf',
    fontSize: 9,
  },
  fleetManagerMessageTimeOnLight: {
    color: '#284525',
  },
  fleetManagerMessageText: {
    color: '#eef6ff',
    fontSize: 12,
    lineHeight: 17,
  },
  fleetManagerMessageTextOnLight: {
    color: '#06130b',
  },
  fleetManagerThinkingRow: {
    alignSelf: 'flex-start',
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: '#0b2033',
    borderWidth: 1,
    borderColor: 'rgba(24, 243, 255, 0.14)',
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  fleetManagerThinkingText: {
    color: HUD.cyanSoft,
    fontSize: 11,
    fontWeight: '900',
  },
  fleetManagerQueueStack: {
    borderTopWidth: 1,
    borderTopColor: 'rgba(24, 243, 255, 0.1)',
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 6,
  },
  fleetManagerQueueRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: '#0b2033',
    borderWidth: 1,
    borderColor: 'rgba(255, 184, 107, 0.18)',
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  fleetManagerQueueText: {
    flex: 1,
    color: '#f4e7c7',
    fontSize: 11,
    fontWeight: '800',
  },
  fleetManagerQueueAction: {
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: '#253018',
    borderWidth: 1,
    borderColor: 'rgba(212, 255, 101, 0.22)',
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  fleetManagerQueueActionText: {
    color: '#e8ffae',
    fontSize: 10,
    fontWeight: '900',
  },
  fleetManagerComposer: {
    borderTopWidth: 1,
    borderTopColor: 'rgba(24, 243, 255, 0.12)',
    padding: 10,
    gap: 8,
  },
  fleetManagerComposerMenu: {
    maxHeight: 420,
    gap: 8,
  },
  fleetManagerComposerInput: {
    minHeight: 74,
    maxHeight: 140,
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: '#06111f',
    borderWidth: 1,
    borderColor: 'rgba(24, 243, 255, 0.16)',
    color: '#eef7ff',
    paddingHorizontal: 10,
    paddingVertical: 9,
    fontSize: 12,
    lineHeight: 17,
    textAlignVertical: 'top',
  },
  fleetManagerComposerFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  fleetManagerComposerFooterControls: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  fleetManagerComposerStatus: {
    flex: 1,
    color: '#8fa4c4',
    fontSize: 10,
    fontWeight: '800',
  },
  fleetComposerIconButton: {
    width: 28,
    height: 28,
    minWidth: 28,
  },
  fleetManagerSendButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#213d65',
    alignItems: 'center',
    justifyContent: 'center',
  },
  fleetSidebarPanel: {
    flex: 1,
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: '#071322',
    borderWidth: 1,
    borderColor: 'rgba(24, 243, 255, 0.18)',
    padding: 12,
    gap: 12,
  },
  fleetMainScroll: {
    flex: 1,
    minWidth: 0,
  },
  fleetMainContent: {
    paddingBottom: 22,
  },
  fleetPanelHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  fleetPanelHeaderCopy: {
    flex: 1,
    gap: 4,
  },
  fleetEyebrow: {
    color: HUD.cyan,
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0.9,
    textTransform: 'uppercase',
  },
  fleetPanelTitle: {
    color: '#f6fbff',
    fontSize: 17,
    fontWeight: '900',
  },
  fleetPanelText: {
    color: '#8fa4c4',
    fontSize: 11,
    lineHeight: 16,
  },
  fleetIconAction: {
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    borderWidth: 1,
    borderColor: 'rgba(24, 243, 255, 0.22)',
    backgroundColor: '#0b1e31',
    paddingHorizontal: 9,
    paddingVertical: 7,
  },
  fleetIconActionText: {
    color: '#dff8ff',
    fontSize: 10,
    fontWeight: '900',
  },
  panelCollapseButton: {
    width: 34,
    height: 34,
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: '#0b1e31',
    borderWidth: 1,
    borderColor: 'rgba(24, 243, 255, 0.26)',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  panelCollapseButtonText: {
    color: '#eafaff',
    fontSize: 24,
    lineHeight: 28,
    fontWeight: '900',
  },
  fleetStatusCard: {
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: '#081827',
    borderWidth: 1,
    borderColor: 'rgba(24, 243, 255, 0.12)',
    padding: 10,
    gap: 3,
  },
  fleetStatusLabel: {
    color: '#7891b4',
    fontSize: 10,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  fleetStatusText: {
    color: '#e8f3ff',
    fontSize: 12,
    fontWeight: '700',
  },
  fleetStatusError: {
    color: '#ffb8b8',
    fontSize: 12,
    fontWeight: '800',
  },
  fleetCreateCard: {
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: '#081827',
    borderWidth: 1,
    borderColor: 'rgba(24, 243, 255, 0.12)',
    padding: 10,
    gap: 9,
  },
  fleetCollapsedNotice: {
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: '#081827',
    borderWidth: 1,
    borderColor: 'rgba(24, 243, 255, 0.12)',
    padding: 12,
    gap: 5,
  },
  fleetIdentityGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  fleetIdentityChip: {
    minWidth: 136,
    flexGrow: 1,
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: '#06111f',
    borderWidth: 1,
    borderColor: 'rgba(24, 243, 255, 0.14)',
    paddingHorizontal: 10,
    paddingVertical: 9,
    gap: 2,
  },
  fleetIdentityChipActive: {
    backgroundColor: '#12384a',
    borderColor: 'rgba(24, 243, 255, 0.55)',
  },
  fleetIdentityName: {
    color: '#dfefff',
    fontSize: 12,
    fontWeight: '900',
  },
  fleetIdentityNameActive: {
    color: '#ffffff',
  },
  fleetIdentityMeta: {
    color: '#7f95ba',
    fontSize: 10,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  fleetIdentityMetaActive: {
    color: HUD.cyanSoft,
  },
  fleetSectionTitle: {
    color: '#f1f7ff',
    fontSize: 12,
    fontWeight: '900',
  },
  fleetSectionMeta: {
    color: '#8ea5c8',
    fontSize: 11,
    fontWeight: '900',
  },
  fleetInput: {
    minHeight: 36,
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: '#06111f',
    borderWidth: 1,
    borderColor: 'rgba(24, 243, 255, 0.15)',
    color: '#eef7ff',
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontSize: 12,
  },
  fleetInlineInput: {
    flex: 1,
  },
  fleetTaskInput: {
    minHeight: 58,
    textAlignVertical: 'top',
  },
  fleetActionRow: {
    flexDirection: 'row',
    gap: 8,
  },
  fleetPrimaryAction: {
    flex: 1,
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: HUD.cyan,
    paddingHorizontal: 10,
    paddingVertical: 9,
    alignItems: 'center',
  },
  fleetPrimaryActionText: {
    color: '#04111d',
    fontSize: 11,
    fontWeight: '900',
  },
  fleetSecondaryAction: {
    flex: 1,
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: '#0c2034',
    borderWidth: 1,
    borderColor: 'rgba(24, 243, 255, 0.24)',
    paddingHorizontal: 10,
    paddingVertical: 9,
    alignItems: 'center',
  },
  fleetSecondaryActionText: {
    color: '#dcf7ff',
    fontSize: 11,
    fontWeight: '900',
  },
  fleetActionDisabled: {
    opacity: 0.55,
  },
  fleetEnrollmentCard: {
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: '#06111f',
    borderWidth: 1,
    borderColor: 'rgba(255, 184, 107, 0.26)',
    padding: 9,
    gap: 8,
  },
  fleetEnrollmentHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 8,
  },
  fleetEnrollmentLabel: {
    color: '#f5e3c9',
    fontSize: 10,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 0.7,
  },
  fleetEnrollmentMeta: {
    color: HUD.amber,
    fontSize: 10,
    fontWeight: '900',
  },
  fleetEnrollmentToken: {
    color: '#fff1d8',
    fontSize: 12,
    lineHeight: 17,
  },
  fleetWorkersSection: {
    gap: 9,
  },
  fleetWorkersHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 8,
  },
  fleetWorkerList: {
    gap: 10,
  },
  fleetWorkerGrid: {
    gap: 10,
    ...(Platform.OS === 'web'
      ? ({
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fit, minmax(292px, 1fr))',
          alignItems: 'stretch',
        } as any)
      : {
          flexDirection: 'row',
          flexWrap: 'wrap',
        }),
  },
  fleetWorkerCard: {
    minWidth: 0,
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: '#081827',
    borderWidth: 1,
    borderColor: 'rgba(24, 243, 255, 0.15)',
    padding: 10,
    gap: 9,
    ...(Platform.OS === 'web'
      ? null
      : {
          flexBasis: '48%',
          flexGrow: 1,
        }),
  },
  fleetWorkerHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
  },
  fleetWorkerTitleBlock: {
    flex: 1,
    gap: 2,
  },
  fleetWorkerName: {
    color: '#f6fbff',
    fontSize: 14,
    fontWeight: '900',
  },
  fleetWorkerMeta: {
    color: '#8ba1c2',
    fontSize: 10,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  fleetWorkerMenuButton: {
    width: 34,
    height: 34,
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: '#0b2033',
    borderWidth: 1,
    borderColor: 'rgba(24, 243, 255, 0.18)',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  fleetWorkerMenuButtonActive: {
    backgroundColor: '#12384a',
    borderColor: 'rgba(24, 243, 255, 0.48)',
  },
  fleetWorkerMenuIcon: {
    color: '#e7f7ff',
    fontSize: 20,
    fontWeight: '900',
  },
  fleetWorkerMenu: {
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: '#06111f',
    borderWidth: 1,
    borderColor: 'rgba(24, 243, 255, 0.16)',
    padding: 8,
    gap: 8,
  },
  fleetWorkerMenuRenameRow: {
    flexDirection: 'row',
    gap: 8,
  },
  fleetWorkerMenuActionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  fleetWorkerMenuAction: {
    flexGrow: 1,
    minWidth: 94,
  },
  fleetSmallDangerAction: {
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: '#391321',
    borderWidth: 1,
    borderColor: 'rgba(255, 44, 114, 0.32)',
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  fleetSmallDangerActionText: {
    color: '#ffbad0',
    fontSize: 10,
    fontWeight: '900',
  },
  fleetWorkerInfoGrid: {
    gap: 7,
  },
  fleetWorkerInfoTile: {
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: '#06111f',
    borderWidth: 1,
    borderColor: 'rgba(24, 243, 255, 0.1)',
    padding: 8,
    gap: 3,
  },
  fleetInfoLabel: {
    color: '#7d94b8',
    fontSize: 9,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 0.7,
  },
  fleetInfoValue: {
    color: '#edf6ff',
    fontSize: 11,
    lineHeight: 15,
  },
  fleetInfoMeta: {
    color: HUD.cyanSoft,
    fontSize: 10,
    fontWeight: '900',
  },
  sidebarMenuList: {
    gap: 3,
  },
  sidebarMenuRowMinimal: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    minHeight: 28,
    paddingHorizontal: 6,
    paddingVertical: 4,
  },
  sidebarMenuRowMinimalActive: {
    backgroundColor: '#2d2d2d',
  },
  sidebarMenuRowMinimalDisabled: {
    opacity: 0.55,
  },
  sidebarMenuRowGlyph: {
    color: '#9b9b9b',
    fontSize: 13,
    lineHeight: 16,
    width: 18,
    textAlign: 'center',
    ...(SIDEBAR_ICON_STYLE as any),
  },
  sidebarMenuRowLabelMinimal: {
    flex: 1,
    color: '#efefef',
    fontSize: 12,
    fontWeight: '600',
  },
  sidebarMenuRowValueMinimal: {
    color: '#8f8f8f',
    fontSize: 9,
    fontWeight: '700',
  },
  sidebarListSectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  sidebarListSectionTitle: {
    color: '#7f7f7f',
    fontSize: 11,
    fontWeight: '700',
  },
  sidebarSectionActionText: {
    color: '#bdbdbd',
    fontSize: 10,
    fontWeight: '700',
  },
  sidebarSimpleList: {
    gap: 2,
  },
  sidebarSimpleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    minHeight: 30,
    paddingHorizontal: 7,
    paddingVertical: 5,
  },
  sidebarSimpleRowActive: {
    backgroundColor: '#082033',
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
  },
  sidebarSimpleRowCopy: {
    flex: 1,
    gap: 2,
  },
  sidebarRunningRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    flex: 1,
  },
  sidebarRunningDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: '#d4ff65',
  },
  sidebarSimpleRowTitle: {
    color: '#efefef',
    fontSize: 13,
    fontWeight: '600',
  },
  sidebarSimpleRowSubtle: {
    color: '#777',
    fontSize: 10,
  },
  sidebarSimpleRowMeta: {
    color: '#8b8b8b',
    fontSize: 10,
    fontWeight: '700',
  },
  sidebarProjectList: {
    gap: 5,
  },
  sidebarChatsCard: {
    gap: 14,
  },
  sidebarChatsHeader: {
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(24, 243, 255, 0.12)',
    paddingBottom: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
  },
  sidebarChatsHeaderCopy: {
    flex: 1,
    gap: 4,
  },
  sidebarChatsTitle: {
    color: '#f7fbff',
    fontSize: 22,
    fontWeight: '900',
  },
  sidebarChatsText: {
    color: '#8fa5c7',
    fontSize: 12,
    lineHeight: 18,
  },
  sidebarChatsCloseButton: {
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: '#17253f',
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  sidebarChatsCloseText: {
    color: '#dbe7fb',
    fontWeight: '900',
    fontSize: 12,
  },
  sidebarChatActionRow: {
    flexDirection: 'row',
    gap: 10,
  },
  secondaryRailButtonCompact: {
    minWidth: 112,
  },
  sidebarSearchCard: {
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: '#071827',
    borderWidth: 1,
    borderColor: 'rgba(24, 243, 255, 0.13)',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  sidebarSearchInput: {
    color: '#edf5ff',
    fontSize: 14,
    paddingVertical: 0,
  },
  sidebarSearchModalOverlay: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: 'rgba(4, 9, 18, 0.62)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 36,
    paddingVertical: 32,
    zIndex: 80,
  },
  sidebarSearchModalCard: {
    width: '100%',
    maxWidth: 620,
    maxHeight: '72%',
    backgroundColor: '#262626',
    borderRadius: 22,
    paddingHorizontal: 12,
    paddingVertical: 12,
    gap: 8,
  },
  folderChoiceOverlay: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: 'rgba(4, 9, 18, 0.68)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 36,
    paddingVertical: 32,
    zIndex: 90,
  },
  folderChoiceCard: {
    width: '100%',
    maxWidth: 520,
    borderRadius: 18,
    backgroundColor: '#0b1324',
    borderWidth: 1,
    borderColor: '#253a61',
    paddingHorizontal: 18,
    paddingVertical: 16,
    gap: 14,
  },
  folderChoiceHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  folderChoiceTitle: {
    color: '#f5f9ff',
    fontSize: 18,
    fontWeight: '800',
  },
  folderChoiceCloseButton: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#17233a',
  },
  folderChoiceCloseText: {
    color: '#dfe8f7',
    fontSize: 12,
    fontWeight: '900',
  },
  folderChoiceText: {
    color: '#a7badc',
    lineHeight: 20,
  },
  folderChoiceActions: {
    gap: 10,
  },
  folderChoiceAction: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#253a61',
    backgroundColor: '#101c30',
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 4,
  },
  folderChoiceActionPrimary: {
    borderColor: '#3e66a2',
    backgroundColor: '#162844',
  },
  folderChoiceActionDisabled: {
    opacity: 0.62,
  },
  folderChoiceActionText: {
    color: '#f0f6ff',
    fontWeight: '800',
  },
  folderChoiceActionTextPrimary: {
    color: '#ffffff',
  },
  folderChoiceActionHint: {
    color: '#8da1c2',
    fontSize: 12,
    lineHeight: 17,
  },
  sidebarChatTooltipLayer: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    zIndex: 40,
  },
  sidebarChatTooltipCard: {
    position: 'absolute',
    width: 296,
    borderRadius: 18,
    backgroundColor: '#2c2c2c',
    paddingHorizontal: 14,
    paddingVertical: 11,
    gap: 4,
  },
  sidebarChatTooltipTitle: {
    color: '#f5f5f5',
    fontSize: 15,
    fontWeight: '700',
  },
  sidebarChatTooltipMeta: {
    color: '#c8c8c8',
    fontSize: 12,
    lineHeight: 16,
  },
  sidebarChatTooltipMetaSecondary: {
    color: '#979797',
    fontSize: 12,
    lineHeight: 16,
  },
  sidebarSearchModalInputShell: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderRadius: 16,
    backgroundColor: '#333333',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  sidebarSearchModalInputGlyph: {
    color: '#9a9a9a',
    fontSize: 13,
  },
  sidebarSearchModalInput: {
    flex: 1,
    color: '#f5f5f5',
    fontSize: 15,
    paddingVertical: 0,
  },
  sidebarSearchSectionLabel: {
    color: '#8e8e8e',
    fontSize: 12,
    fontWeight: '600',
    paddingHorizontal: 6,
  },
  sidebarSearchEmptyState: {
    paddingVertical: 18,
    paddingHorizontal: 6,
    gap: 6,
  },
  sidebarSearchEmptyTitle: {
    color: '#eef6ff',
    fontSize: 15,
    fontWeight: '700',
  },
  sidebarSearchEmptyText: {
    color: '#8ca4c8',
    fontSize: 13,
    lineHeight: 20,
  },
  sidebarSearchResultsScroll: {
    flexGrow: 0,
  },
  sidebarSearchResultsList: {
    gap: 4,
    paddingBottom: 6,
  },
  sidebarSearchResultRow: {
    backgroundColor: '#383838',
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  sidebarSearchResultLine: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  sidebarSearchResultPrimary: {
    flex: 1,
    color: '#f5f5f5',
    fontSize: 14,
    fontWeight: '700',
  },
  sidebarSearchResultSecondary: {
    maxWidth: '34%',
    color: '#a4a4a4',
    fontSize: 12,
    fontWeight: '500',
  },
  sidebarPinnedSection: {
    gap: 10,
  },
  sidebarSectionTitle: {
    color: '#f7fbff',
    fontSize: 15,
    fontWeight: '900',
  },
});
