import { Platform, StyleSheet } from 'react-native';

import { desktopAppShellVisualStyles } from './DesktopAppShell.visualStyles';
import { DESKTOP_RECT_BUTTON_RADIUS } from './desktopUiTokens';
import { mergeDesktopVisualStyles } from './mergeDesktopVisualStyles';

const baseStyles = StyleSheet.create({
  page: {
    flex: 1,
    backgroundColor: '#050b14',
  },
  startupPage: {
    flex: 1,
    backgroundColor: '#050b14',
    paddingHorizontal: 24,
    paddingVertical: 28,
    justifyContent: 'center',
  },
  startupSetupShell: {
    width: '100%',
    maxWidth: 1120,
    alignSelf: 'center',
  },
  startupGateCard: {
    width: '100%',
    maxWidth: 560,
    alignSelf: 'center',
    alignItems: 'center',
    gap: 14,
    paddingHorizontal: 28,
    paddingVertical: 34,
    borderRadius: 14,
    backgroundColor: '#071322',
    borderWidth: 1,
    borderColor: 'rgba(24, 243, 255, 0.18)',
  },
  startupGateTitle: {
    color: '#f6fbff',
    fontSize: 24,
    fontWeight: '800',
    textAlign: 'center',
  },
  startupGateText: {
    color: '#97add3',
    fontSize: 14,
    lineHeight: 21,
    textAlign: 'center',
    maxWidth: 420,
  },
  startupHintText: {
    color: '#6f86ab',
    fontSize: 12,
    lineHeight: 18,
    textAlign: 'center',
    maxWidth: 420,
  },
  startupIssueRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    flexWrap: 'wrap',
    maxWidth: 460,
  },
  accountModeRow: {
    flexDirection: 'row',
    gap: 8,
    backgroundColor: '#0b1a2e',
    borderWidth: 1,
    borderColor: '#203758',
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    padding: 4,
  },
  accountModeButton: {
    minWidth: 104,
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    paddingHorizontal: 12,
    paddingVertical: 8,
    alignItems: 'center',
  },
  accountModeButtonActive: {
    backgroundColor: '#18f3ff',
  },
  accountModeText: {
    color: '#a9bad7',
    fontSize: 12,
    fontWeight: '800',
  },
  accountModeTextActive: {
    color: '#03111d',
  },
  accountInput: {
    width: '100%',
    maxWidth: 380,
    minHeight: 44,
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    borderWidth: 1,
    borderColor: '#263b5f',
    backgroundColor: '#091728',
    color: '#f6fbff',
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  accountPasswordInputRow: {
    width: '100%',
    maxWidth: 380,
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    borderWidth: 1,
    borderColor: '#263b5f',
    backgroundColor: '#091728',
  },
  accountPasswordInput: {
    flex: 1,
    width: 0,
    minHeight: 42,
    borderWidth: 0,
    backgroundColor: 'transparent',
  },
  accountPeekButton: {
    minHeight: 42,
    minWidth: 60,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  accountPeekButtonText: {
    color: '#18f3ff',
    fontSize: 12,
    fontWeight: '800',
  },
  accountPasswordChecklist: {
    width: '100%',
    maxWidth: 380,
    gap: 4,
  },
  accountPasswordRequirement: {
    color: '#ffb4b4',
    fontSize: 11,
    lineHeight: 16,
    fontWeight: '700',
    textAlign: 'left',
  },
  accountPasswordRequirementMet: {
    color: '#8ee6b0',
  },
  rememberRow: {
    width: '100%',
    maxWidth: 380,
    minHeight: 34,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
  },
  rememberBox: {
    width: 18,
    height: 18,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#4d648d',
    backgroundColor: '#091728',
    alignItems: 'center',
    justifyContent: 'center',
  },
  rememberBoxActive: {
    backgroundColor: '#18f3ff',
    borderColor: '#18f3ff',
  },
  rememberCheck: {
    color: '#03111d',
    fontSize: 12,
    fontWeight: '900',
    lineHeight: 14,
  },
  rememberText: {
    color: '#b8c7e6',
    fontSize: 12,
    fontWeight: '700',
  },
  startupActionRow: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 6,
    flexWrap: 'wrap',
    justifyContent: 'center',
  },
  startupPrimaryButton: {
    minWidth: 160,
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    paddingHorizontal: 18,
    paddingVertical: 12,
    backgroundColor: '#18f3ff',
    alignItems: 'center',
  },
  startupPrimaryButtonDisabled: {
    opacity: 0.55,
  },
  startupPrimaryButtonText: {
    color: '#03111d',
    fontSize: 13,
    fontWeight: '800',
  },
  startupGoogleButton: {
    minWidth: 220,
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: '#d8e0f0',
    backgroundColor: '#ffffff',
    alignItems: 'center',
  },
  startupGoogleButtonText: {
    color: '#172033',
    fontSize: 13,
    fontWeight: '800',
  },
  startupSecondaryButton: {
    minWidth: 140,
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: '#30456d',
    backgroundColor: '#13203a',
    alignItems: 'center',
  },
  startupSecondaryButtonText: {
    color: '#d7e7ff',
    fontSize: 13,
    fontWeight: '700',
  },
  startupOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#07111f',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 50,
  },
  conversationBootShell: {
    flex: 1,
  },
  skeletonShell: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: '#07111f',
  },
  skeletonMain: {
    flex: 1,
    paddingHorizontal: 76,
    paddingVertical: 30,
    gap: 16,
  },
  skeletonTranscript: {
    flex: 1,
    borderRadius: 28,
    backgroundColor: '#101a31',
    borderWidth: 1,
    borderColor: '#142744',
    padding: 24,
  },
  skeletonMessageStack: {
    flex: 1,
    justifyContent: 'center',
    gap: 24,
  },
  skeletonMessageRow: {
    gap: 9,
  },
  skeletonMessageRowLeft: {
    width: '58%',
  },
  skeletonMessageRowLeftWide: {
    width: '66%',
  },
  skeletonMessageRowRight: {
    width: '42%',
    alignSelf: 'flex-end',
    alignItems: 'flex-end',
  },
  skeletonBlock: {
    backgroundColor: '#223252',
    borderRadius: 6,
    opacity: 0.62,
    overflow: 'hidden',
  },
  skeletonGlint: {
    position: 'absolute',
    top: -18,
    bottom: -18,
    width: 84,
    backgroundColor: 'rgba(238, 247, 255, 0.22)',
    ...(Platform.OS === 'web'
      ? ({
          backgroundImage: 'linear-gradient(90deg, transparent 0%, rgba(238, 247, 255, 0.08) 24%, rgba(255, 255, 255, 0.42) 50%, rgba(238, 247, 255, 0.08) 76%, transparent 100%)',
        } as any)
      : null),
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderLeftColor: 'rgba(255, 255, 255, 0.12)',
    borderRightColor: 'rgba(255, 255, 255, 0.04)',
  },
  skeletonTinyLine: {
    width: 74,
    height: 10,
    opacity: 0.5,
  },
  skeletonLongLine: {
    width: '100%',
    height: 14,
  },
  skeletonMediumLine: {
    width: '72%',
    height: 14,
  },
  skeletonShortBubble: {
    width: '86%',
    height: 46,
    borderRadius: 18,
  },
  skeletonComposer: {
    minHeight: 110,
    borderRadius: 28,
    backgroundColor: '#101a31',
    borderWidth: 1,
    borderColor: '#142744',
    padding: 20,
    justifyContent: 'space-between',
  },
  skeletonComposerLine: {
    width: '46%',
    height: 14,
  },
  skeletonComposerFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  skeletonComposerChip: {
    width: 145,
    height: 12,
  },
  skeletonComposerChipShort: {
    width: 84,
    height: 12,
  },
  skeletonSendButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    marginLeft: 'auto',
  },
  skeletonRail: {
    width: 300,
    borderLeftWidth: 1,
    borderLeftColor: '#1d2a44',
    backgroundColor: '#081324',
    paddingHorizontal: 16,
    paddingVertical: 26,
    gap: 18,
  },
  skeletonRailIcon: {
    width: 22,
    height: 22,
    borderRadius: 11,
    alignSelf: 'center',
  },
  skeletonRailSection: {
    gap: 12,
    marginTop: 10,
  },
  skeletonRailHeading: {
    width: 92,
    height: 11,
  },
  skeletonRailSearch: {
    width: '100%',
    height: 38,
    borderRadius: 8,
  },
  skeletonRailLine: {
    width: '84%',
    height: 12,
  },
  skeletonRailLineShort: {
    width: '62%',
    height: 12,
  },
  skeletonRailRow: {
    width: '78%',
    height: 14,
  },
  skeletonRailRowActive: {
    width: '94%',
    height: 28,
    borderRadius: 8,
  },
  startupOverlayCard: {
    alignItems: 'center',
    justifyContent: 'center',
    gap: 14,
    paddingHorizontal: 28,
    paddingVertical: 30,
    borderRadius: 28,
    backgroundColor: 'rgba(15, 23, 45, 0.88)',
    borderWidth: 1,
    borderColor: '#223052',
    minWidth: 300,
  },
  startupOverlayTitle: {
    color: '#f6fbff',
    fontSize: 24,
    fontWeight: '800',
  },
  startupOverlayText: {
    color: '#8ea4cb',
    fontSize: 14,
    textAlign: 'center',
  },
  setupOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 45,
  },
  setupOverlayBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(4, 10, 20, 0.42)',
  },
  setupOverlayFrame: {
    ...StyleSheet.absoluteFillObject,
    paddingHorizontal: 24,
    paddingVertical: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  setupOverlaySurface: {
    width: '100%',
    maxWidth: 1320,
    maxHeight: '92%',
    shadowColor: '#01040b',
    shadowOpacity: 0.38,
    shadowRadius: 26,
    shadowOffset: { width: 0, height: 18 },
    elevation: 20,
  },
  startupGlyphFrame: {
    width: 74,
    height: 74,
    alignItems: 'center',
    justifyContent: 'center',
  },
  startupGlyphCore: {
    position: 'absolute',
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#173158',
    borderWidth: 1,
    borderColor: '#284a81',
  },
  startupGlyphOrbit: {
    width: 66,
    height: 66,
    borderRadius: 33,
    borderWidth: 1,
    borderColor: '#284064',
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingTop: 3,
  },
  startupGlyphDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#d4ff65',
  },
  windowChromeBar: {
    height: 34,
    minHeight: 34,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingLeft: 5,
    paddingRight: 146,
    backgroundColor: '#202020',
    borderBottomWidth: 1,
    borderBottomColor: '#151515',
    overflow: 'visible',
    position: 'relative',
    zIndex: 1000,
    elevation: 1000,
  },
  windowChromeLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    minWidth: 0,
  },
  windowChromeRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    position: 'relative',
    zIndex: 1100,
    elevation: 1100,
  },
  windowChromeIconButton: {
    width: 28,
    height: 26,
    borderRadius: 7,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: 'transparent',
  },
  windowChromeButtonSubtle: {
    opacity: 0.68,
  },
  windowChromeButtonHovered: {
    backgroundColor: '#2b2b2b',
    borderColor: '#343434',
  },
  windowChromeButtonPressed: {
    transform: [{ scale: 0.96 }],
  },
  windowChromeIconText: {
    color: '#b8b8b8',
    fontSize: 15,
    lineHeight: 18,
    fontWeight: '700',
  },
  windowChromeMenuButton: {
    height: 26,
    borderRadius: 6,
    paddingHorizontal: 8,
    justifyContent: 'center',
  },
  windowChromeMenuButtonHovered: {
    backgroundColor: '#2b2b2b',
  },
  windowChromeMenuText: {
    color: '#9e9e9e',
    fontSize: 13,
    lineHeight: 17,
    fontWeight: '500',
  },
  windowChromeUpdateButton: {
    backgroundColor: '#1a3440',
    borderColor: '#246072',
  },
  windowChromeUpdateText: {
    color: '#74e8ff',
    fontSize: 17,
    lineHeight: 19,
    fontWeight: '900',
  },
  headerSurfaceTabs: {
    height: 26,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    borderRadius: 8,
    padding: 2,
    backgroundColor: '#171717',
    borderWidth: 1,
    borderColor: '#343434',
  },
  headerSurfaceTab: {
    height: 20,
    minWidth: 50,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  headerSurfaceTabHovered: {
    backgroundColor: '#2b2b2b',
  },
  headerSurfaceTabActive: {
    backgroundColor: '#d4ff65',
  },
  headerSurfaceTabText: {
    color: '#a8a8a8',
    fontSize: 11,
    lineHeight: 14,
    fontWeight: '800',
  },
  headerSurfaceTabTextActive: {
    color: '#081324',
  },
  headerIdentityStopButton: {
    minHeight: 26,
    borderRadius: 8,
    paddingHorizontal: 10,
    justifyContent: 'center',
    borderWidth: 1,
    backgroundColor: '#4b1424',
    borderColor: 'rgba(255, 64, 119, 0.5)',
  },
  headerIdentityStopButtonHovered: {
    backgroundColor: '#67182d',
    borderColor: 'rgba(255, 91, 143, 0.72)',
  },
  headerIdentityStopText: {
    color: '#ffd1de',
    fontSize: 12,
    fontWeight: '900',
  },
  windowChromeStopButton: {
    minHeight: 26,
    borderRadius: 8,
    paddingHorizontal: 10,
    justifyContent: 'center',
    borderWidth: 1,
  },
  windowChromeStopButtonActive: {
    backgroundColor: '#5f3440',
    borderColor: '#7a4250',
  },
  windowChromeStartButton: {
    backgroundColor: '#27321f',
    borderColor: '#435934',
  },
  windowChromeStopText: {
    color: '#ccebbd',
    fontSize: 12,
    fontWeight: '800',
  },
  windowChromeStopTextActive: {
    color: '#f6fbff',
  },
  windowChromeSettingsButton: {
    width: 30,
    height: 26,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'transparent',
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
  },
  windowChromeSettingsButtonActive: {
    backgroundColor: '#2b2b2b',
    borderColor: '#3a3a3a',
  },
  /* ── Compact header bar ── */
  headerBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 8,
    backgroundColor: '#071322',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(24, 243, 255, 0.16)',
    minHeight: 48,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  statusDotOnline: {
    backgroundColor: '#4ade80',
  },
  statusDotOffline: {
    backgroundColor: '#6b7280',
  },
  headerTitle: {
    color: '#f6fbff',
    fontSize: 15,
    fontWeight: '800',
  },
  headerMeta: {
    color: '#7f97bc',
    fontSize: 13,
  },
  telegramBadge: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderWidth: 1,
  },
  telegramBadgeReady: {
    backgroundColor: '#102c24',
    borderColor: '#235545',
  },
  telegramBadgeStarting: {
    backgroundColor: '#13203a',
    borderColor: '#33507d',
  },
  telegramBadgeWarning: {
    backgroundColor: '#382812',
    borderColor: '#735123',
  },
  telegramBadgeMuted: {
    backgroundColor: '#111827',
    borderColor: '#374151',
  },
  telegramBadgeOffline: {
    backgroundColor: '#2c1620',
    borderColor: '#5c2a3d',
  },
  telegramBadgeText: {
    color: '#dce8ff',
    fontSize: 11,
    fontWeight: '700',
  },
  headerSession: {
    color: '#5472a4',
    fontSize: 12,
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    position: 'relative',
  },
  headerVersion: {
    color: '#5472a4',
    fontSize: 12,
    fontVariant: ['tabular-nums'],
  },
  headerIconButton: {
    width: 40,
    height: 40,
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS + 2,
    borderWidth: 1,
    borderColor: 'rgba(24, 243, 255, 0.18)',
    backgroundColor: '#0d1b2d',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerIconButtonHovered: {
    borderColor: 'rgba(24, 243, 255, 0.42)',
    backgroundColor: '#10233a',
  },
  headerIconButtonPressed: {
    transform: [{ scale: 0.96 }],
  },
  headerIconButtonMuted: {
    opacity: 0.76,
  },
  headerUpdateButton: {
    backgroundColor: '#19e6f2',
    borderColor: 'rgba(153, 246, 255, 0.78)',
  },
  headerUpdateIcon: {
    color: '#04111f',
    fontSize: 20,
    lineHeight: 22,
    fontWeight: '900',
    fontVariant: ['tabular-nums'],
  },
  headerCheckingIcon: {
    color: '#9fb4d8',
    fontSize: 16,
    fontWeight: '900',
  },
  headerActionButton: {
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    minHeight: 34,
    paddingHorizontal: 13,
    paddingVertical: 6,
    backgroundColor: '#d4ff65',
  },
  headerActionPrimary: {
    backgroundColor: '#d4ff65',
  },
  headerActionWarn: {
    backgroundColor: '#5f3440',
  },
  headerActionDisabled: {
    opacity: 0.5,
  },
  headerActionText: {
    color: '#081324',
    fontSize: 12,
    fontWeight: '800',
  },
  headerActionTextLight: {
    color: '#f6fbff',
  },
  accountMenuShell: {
    position: 'relative',
    zIndex: 1200,
    elevation: 1200,
  },
  headerSettingsButton: {
    minWidth: 112,
    minHeight: 40,
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS + 2,
    paddingHorizontal: 11,
    paddingVertical: 8,
    backgroundColor: '#10131a',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: 8,
  },
  headerSettingsButtonHovered: {
    backgroundColor: '#171b24',
    borderColor: 'rgba(255, 255, 255, 0.16)',
  },
  headerSettingsButtonActive: {
    backgroundColor: '#1c2029',
    borderColor: 'rgba(24, 243, 255, 0.32)',
  },
  headerSettingsGlyph: {
    color: '#dce8ff',
    fontSize: 15,
    lineHeight: 18,
    fontWeight: '800',
  },
  headerSettingsText: {
    color: '#f4f7fb',
    fontSize: 12,
    fontWeight: '800',
  },
  accountMenuPopover: {
    position: 'absolute',
    right: 0,
    top: 30,
    width: 282,
    borderRadius: 14,
    backgroundColor: '#1d2027',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    padding: 8,
    gap: 4,
    zIndex: 1300,
    shadowColor: '#000',
    shadowOpacity: 0.32,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 14 },
    elevation: 18,
  },
  accountMenuHeader: {
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.08)',
    marginBottom: 3,
  },
  accountMenuEmail: {
    color: '#eef4ff',
    fontSize: 13,
    fontWeight: '800',
  },
  accountMenuSubtext: {
    color: '#a7b4c8',
    fontSize: 11,
    fontWeight: '700',
    marginTop: 2,
  },
  accountMenuRow: {
    minHeight: 40,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  accountMenuRowHovered: {
    backgroundColor: 'rgba(255, 255, 255, 0.07)',
  },
  accountMenuRowDanger: {
    marginTop: 2,
  },
  accountMenuRowDangerHovered: {
    backgroundColor: 'rgba(255, 89, 139, 0.12)',
  },
  accountMenuIcon: {
    width: 18,
    color: '#d8dfeb',
    fontSize: 14,
    lineHeight: 17,
    textAlign: 'center',
  },
  accountMenuLabel: {
    color: '#f3f6fb',
    fontSize: 12,
    fontWeight: '800',
  },
  /* ── Status banners ── */
  statusBanner: {
    minHeight: 34,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderBottomWidth: 1,
  },
  errorBanner: {
    backgroundColor: '#3a1620',
    borderBottomColor: '#6a3040',
  },
  statusBannerText: {
    flex: 1,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '700',
  },
  errorBannerText: {
    color: '#ffd3db',
  },
  noticeBanner: {
    backgroundColor: '#102c24',
    borderBottomColor: '#235545',
  },
  noticeBannerText: {
    color: '#c9f7df',
  },
  statusBannerActionButton: {
    minHeight: 24,
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    paddingHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: 'rgba(255,255,255,0.16)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.18)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  statusBannerActionButtonDisabled: {
    opacity: 0.55,
  },
  statusBannerActionText: {
    color: '#f6fbff',
    fontSize: 12,
    fontWeight: '800',
  },
  statusBannerCloseButton: {
    width: 28,
    height: 24,
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.12)',
  },
  statusBannerCloseText: {
    color: '#f6fbff',
    fontSize: 14,
    fontWeight: '900',
    lineHeight: 16,
  },
  /* ── Collapsible controls panel ── */
  controlsPanel: {
    backgroundColor: '#0f182e',
    borderBottomWidth: 1,
    borderBottomColor: '#1e2b47',
    maxHeight: 280,
  },
  controlsPanelHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 4,
  },
  controlsPanelTitle: {
    color: '#f6fbff',
    fontSize: 18,
    fontWeight: '800',
  },
  controlsPanelCloseButton: {
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: '#1a2a48',
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  controlsPanelCloseText: {
    color: '#cfe0ff',
    fontSize: 12,
    fontWeight: '800',
  },
  controlsPanelScroll: {
    flex: 1,
  },
  controlsPanelContent: {
    padding: 16,
    gap: 16,
  },
  controlsSection: {
    gap: 8,
  },
  controlsSectionTitle: {
    color: '#7f97bc',
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  controlsButtonRow: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
  },
  controlsButton: {
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: '#1a2a48',
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  controlsButtonActive: {
    backgroundColor: '#d4ff65',
  },
  controlsButtonDisabled: {
    opacity: 0.45,
  },
  controlsButtonText: {
    color: '#cfe0ff',
    fontSize: 13,
    fontWeight: '700',
  },
  controlsButtonTextActive: {
    color: '#081324',
  },
  controlsDetailText: {
    color: '#b7c9e8',
    fontSize: 13,
    lineHeight: 19,
  },
  controlsMetaText: {
    color: '#7f97bc',
    fontSize: 12,
  },
  controlsUpdateButton: {
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: '#d4ff65',
    paddingHorizontal: 14,
    paddingVertical: 8,
    alignSelf: 'flex-start',
  },
  controlsUpdateButtonText: {
    color: '#081324',
    fontWeight: '800',
    fontSize: 13,
  },
  /* ── Main content area ── */
  tabBody: {
    flex: 1,
  },
  runtimeWaitShell: {
    flex: 1,
    position: 'relative',
    backgroundColor: '#07111f',
  },
  runtimeWaitOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 28,
    backgroundColor: 'rgba(7, 17, 31, 0.34)',
  },
  loadingCard: {
    flex: 1,
    backgroundColor: '#101a31',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
    gap: 10,
  },
  runtimeWaitCard: {
    flex: 0,
    width: '100%',
    maxWidth: 720,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#25375a',
    backgroundColor: 'rgba(16, 26, 49, 0.92)',
    shadowColor: '#020711',
    shadowOpacity: 0.32,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 16 },
  },
  loadingTitle: {
    color: '#f6fbff',
    fontSize: 22,
    fontWeight: '800',
    textAlign: 'center',
  },
  loadingText: {
    color: '#9db1d2',
    textAlign: 'center',
    maxWidth: 640,
    lineHeight: 21,
  },
  offlineMetaCard: {
    width: '100%',
    maxWidth: 720,
    borderRadius: 20,
    backgroundColor: '#0a1324',
    borderWidth: 1,
    borderColor: '#1e2b47',
    padding: 18,
    gap: 6,
  },
  offlineMetaLabel: {
    color: '#8ea4cb',
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  offlineMetaValue: {
    color: '#f6fbff',
    fontSize: 20,
    fontWeight: '800',
  },
  offlineMetaText: {
    color: '#9db1d2',
    lineHeight: 20,
  },
  offlineActionRow: {
    flexDirection: 'row',
    gap: 10,
  },
  runtimeButton: {
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: '#d4ff65',
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  runtimeButtonDisabled: {
    opacity: 0.7,
  },
  runtimeButtonText: {
    color: '#081324',
    fontWeight: '800',
  },
  secondaryRuntimeButton: {
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: '#17253f',
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  secondaryRuntimeButtonText: {
    color: '#d4e2fb',
    fontWeight: '800',
  },
  /* ── Remote tab ── */
  remoteBody: {
    gap: 16,
    padding: 16,
  },
  remoteIntro: {
    borderRadius: 20,
    backgroundColor: '#111c32',
    borderWidth: 1,
    borderColor: '#1e2e52',
    padding: 20,
    gap: 8,
  },
  remoteIntroTitle: {
    color: '#f6fbff',
    fontSize: 20,
    fontWeight: '800',
  },
  remoteIntroText: {
    color: '#a7bbdc',
    lineHeight: 21,
  },
  remoteActionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 6,
  },
  remotePrimaryButton: {
    minHeight: 44,
    justifyContent: 'center',
    borderRadius: 10,
    backgroundColor: '#17c8e8',
    paddingHorizontal: 16,
  },
  remotePrimaryButtonText: {
    color: '#061322',
    fontWeight: '800',
  },
  remoteSecondaryButton: {
    minHeight: 44,
    justifyContent: 'center',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#34557f',
    paddingHorizontal: 16,
  },
  remoteSecondaryButtonText: {
    color: '#d8e9ff',
    fontWeight: '700',
  },
  remoteEnrollment: {
    marginTop: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#2f5974',
    backgroundColor: '#0a1529',
    padding: 12,
    gap: 5,
  },
  remoteEnrollmentLabel: {
    color: '#91aacd',
    fontSize: 10,
    fontWeight: '800',
  },
  remoteEnrollmentCode: {
    color: '#70e4f6',
    fontSize: 18,
    fontWeight: '800',
    letterSpacing: 1,
  },
  remoteEmpty: {
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: '#2a4165',
    borderRadius: 16,
    padding: 20,
    gap: 6,
  },
  remoteCard: {
    borderRadius: 20,
    backgroundColor: '#0f182e',
    borderWidth: 1,
    borderColor: '#1d2b49',
    padding: 18,
    gap: 12,
  },
  remoteHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  remoteTitle: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '800',
  },
  remoteMeta: {
    color: '#94abd1',
  },
  remoteStatusBadge: {
    borderRadius: 999,
    backgroundColor: '#233656',
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  remoteStatusText: {
    color: '#a8dbff',
    fontWeight: '800',
    textTransform: 'uppercase',
    fontSize: 11,
  },
  remoteDetail: {
    color: '#a7bbdc',
    lineHeight: 20,
  },
  remoteDetailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
  },
  remoteReport: {
    borderRadius: 10,
    backgroundColor: '#111e35',
    padding: 12,
    gap: 5,
  },
  remoteSectionLabel: {
    color: '#73d9eb',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.8,
  },
  remoteWorker: {
    borderTopWidth: 1,
    borderTopColor: '#21304e',
    paddingTop: 12,
    gap: 10,
  },
  remoteWorkerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    flexWrap: 'wrap',
  },
  remoteWorkerIdentity: {
    flex: 1,
    minWidth: 180,
  },
  remoteWorkerName: {
    color: '#edf6ff',
    fontWeight: '700',
  },
  remotePreviewButton: {
    minHeight: 44,
    justifyContent: 'center',
    borderRadius: 9,
    borderWidth: 1,
    borderColor: '#34557f',
    paddingHorizontal: 14,
  },
  remoteButtonDisabled: {
    opacity: 0.45,
  },
  remotePreviewPanel: {
    borderRadius: 10,
    overflow: 'hidden',
    backgroundColor: '#091221',
    padding: 10,
    gap: 8,
  },
  remotePreviewImage: {
    width: '100%',
    height: 300,
    backgroundColor: '#050b14',
  },
  remoteErrorText: {
    color: '#ff9b9b',
  },
});

export const styles = mergeDesktopVisualStyles(baseStyles, desktopAppShellVisualStyles);
