import { Platform, StyleSheet } from 'react-native';

import { DESKTOP_RECT_BUTTON_RADIUS } from './desktopUiTokens';
import { COMPOSER_LINE_HEIGHT, COMPOSER_MAX_HEIGHT, COMPOSER_MIN_HEIGHT, HUD } from './DesktopConversationView.styleConstants';

export const desktopConversationStylesPart3 = StyleSheet.create({
  completedTaskBoardsEyebrow: {
    color: '#7ca6ea',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  completedTaskBoardsTitle: {
    color: '#e6eefc',
    fontSize: 14,
    fontWeight: '800',
  },
  completedTaskBoardsSummary: {
    color: '#8fa8cf',
    fontSize: 12,
    fontWeight: '700',
  },
  completedTaskBoardsList: {
    gap: 10,
  },
  completedTaskCard: {
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: '#0d162b',
    borderWidth: 1,
    borderColor: '#1f3559',
    overflow: 'hidden',
  },
  completedTaskCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    paddingHorizontal: 14,
    paddingVertical: 13,
  },
  completedTaskCardCopy: {
    flex: 1,
    gap: 4,
  },
  completedTaskCardTitle: {
    color: '#f2f7ff',
    fontSize: 13,
    fontWeight: '800',
    lineHeight: 18,
  },
  completedTaskCardMeta: {
    color: '#92add8',
    fontSize: 11,
    lineHeight: 17,
  },
  completedTaskCardToggle: {
    color: '#a9c8ff',
    fontSize: 11,
    fontWeight: '900',
  },
  completedTaskCardBody: {
    borderTopWidth: 1,
    borderTopColor: '#173051',
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 12,
  },
  completedTaskCardSteps: {
    gap: 9,
  },
  completedTaskCardSummaryBox: {
    borderRadius: 0,
    backgroundColor: '#101c35',
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 4,
  },
  completedTaskCardSummaryLabel: {
    color: '#8eaee1',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.7,
    textTransform: 'uppercase',
  },
  completedTaskCardSummaryText: {
    color: '#e5eefc',
    fontSize: 12,
    lineHeight: 18,
  },
  panelToggleButton: {
    borderRadius: 999,
    backgroundColor: '#193054',
    borderWidth: 1,
    borderColor: '#2b4b7c',
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  panelToggleButtonActive: {
    backgroundColor: '#d4ff65',
    borderColor: '#d4ff65',
  },
  panelToggleButtonText: {
    color: '#d8e7ff',
    fontWeight: '800',
    fontSize: 12,
  },
  panelToggleButtonTextActive: {
    color: '#0b1325',
  },
  sidebarMenu: {
    gap: 8,
  },
  sidebarMenuHeader: {
    paddingHorizontal: 4,
    paddingBottom: 8,
    gap: 5,
  },
  sidebarMenuTitle: {
    color: '#f7fbff',
    fontSize: 20,
    fontWeight: '900',
    lineHeight: 25,
  },
  sidebarMenuText: {
    color: '#8fa5c7',
    fontSize: 12,
    lineHeight: 17,
  },
  sidebarMenuRow: {
    minHeight: 54,
    borderRadius: 0,
    borderBottomWidth: 1,
    borderBottomColor: '#1d2946',
    paddingHorizontal: 4,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  sidebarMenuRowActive: {
    borderBottomColor: '#d4ff65',
  },
  sidebarMenuRowDisabled: {
    opacity: 0.45,
  },
  sidebarMenuRowLabel: {
    color: '#f4f8ff',
    fontSize: 15,
    fontWeight: '800',
  },
  sidebarMenuRowValue: {
    color: '#87a3d4',
    fontSize: 12,
    fontWeight: '800',
    textAlign: 'right',
    textTransform: 'uppercase',
  },
  sidebarMenuCloseRow: {
    marginTop: 4,
    paddingHorizontal: 4,
    paddingVertical: 12,
  },
  sidebarMenuCloseText: {
    color: '#73e0ff',
    fontWeight: '900',
  },
  headerToggleRow: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
  },
  headerToggleChip: {
    borderRadius: 999,
    backgroundColor: '#dbe5ff',
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  headerToggleChipActive: {
    backgroundColor: '#0c1d38',
  },
  headerToggleChipText: {
    color: '#16345d',
    fontWeight: '800',
    fontSize: 12,
  },
  headerToggleChipTextActive: {
    color: '#f4f8ff',
  },
  statusCluster: {
    flexDirection: 'row',
    gap: 10,
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
  },
  statusPill: {
    minWidth: 110,
    borderRadius: 18,
    backgroundColor: '#dbe5ff',
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 3,
  },
  statusPillLabel: {
    color: '#5c6990',
    fontSize: 11,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  statusPillValue: {
    color: '#10203f',
    fontWeight: '700',
  },
  voicePanel: {
    borderRadius: 24,
    backgroundColor: '#0f172b',
    borderWidth: 1,
    borderColor: '#223652',
    paddingHorizontal: 14,
    paddingVertical: 14,
    gap: 14,
  },
  sidebarInsetDivider: {
    height: 1,
    marginHorizontal: 12,
    backgroundColor: '#263448',
  },
  voicePanelHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 16,
  },
  voicePanelHeaderCopy: {
    flex: 1,
    gap: 5,
  },
  voicePanelHeaderActions: {
    gap: 8,
    alignSelf: 'flex-start',
  },
  voicePanelHeaderAction: {
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: '#183b49',
    paddingHorizontal: 12,
    paddingVertical: 9,
    alignSelf: 'flex-start',
  },
  voicePanelHeaderActionText: {
    color: '#f4fbff',
    fontWeight: '700',
  },
  voiceRibbon: {
    borderRadius: 18,
    backgroundColor: '#0f2a34',
    padding: 14,
    flexDirection: 'column',
    justifyContent: 'flex-start',
    gap: 12,
  },
  voiceRibbonPrimary: {
    flex: 1,
    gap: 5,
  },
  voiceRibbonActions: {
    flexDirection: 'column',
    alignItems: 'stretch',
    gap: 8,
  },
  voiceModeRow: {
    flexDirection: 'row',
    flexWrap: 'nowrap',
    gap: 10,
  },
  voiceLanguageRow: {
    flexDirection: 'row',
    gap: 10,
  },
  voiceLanguageChip: {
    flex: 1,
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: '#10252e',
    paddingHorizontal: 14,
    paddingVertical: 9,
    alignItems: 'center',
    justifyContent: 'center',
  },
  voiceLanguageChipActive: {
    backgroundColor: '#d4ff65',
  },
  voiceLanguageChipText: {
    color: '#c3ebf7',
    fontSize: 12,
    fontWeight: '800',
  },
  voiceLanguageChipTextActive: {
    color: '#10211d',
  },
  voiceModeChip: {
    flex: 1,
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    borderWidth: 1,
    borderColor: '#25566c',
    backgroundColor: '#0d2530',
    paddingHorizontal: 14,
    paddingVertical: 9,
    alignItems: 'center',
    justifyContent: 'center',
  },
  voiceModeChipActive: {
    backgroundColor: '#d4ff65',
    borderColor: '#d4ff65',
  },
  voiceModeChipDisabled: {
    opacity: 0.55,
  },
  voiceModeChipText: {
    color: '#c3ebf7',
    fontSize: 13,
    fontWeight: '800',
  },
  voiceModeChipTextActive: {
    color: '#10211d',
  },
  voiceLabel: {
    color: '#8fdaf6',
    fontSize: 12,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  voiceValue: {
    color: '#f3fdff',
    fontSize: 18,
    fontWeight: '800',
  },
  voiceHint: {
    color: '#b7dbe8',
    fontSize: 13,
    lineHeight: 18,
  },
  voiceCollapsedCard: {
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: '#102536',
    borderWidth: 1,
    borderColor: '#23465c',
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 14,
  },
  voiceCollapsedCopy: {
    flex: 1,
    gap: 4,
  },
  voiceCollapsedTitle: {
    color: '#8fdaf6',
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  voiceCollapsedText: {
    color: '#f4fbff',
    fontWeight: '800',
  },
  voiceCollapsedAction: {
    color: '#c3ebf7',
    fontWeight: '700',
  },
  ribbonButton: {
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: '#1f5266',
    paddingHorizontal: 14,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  ribbonButtonActive: {
    backgroundColor: '#2f7d5d',
  },
  ribbonButtonMuted: {
    backgroundColor: '#29414b',
  },
  ribbonButtonDisabled: {
    opacity: 0.45,
  },
  ribbonButtonText: {
    color: '#f4fbff',
    fontWeight: '700',
    textAlign: 'center',
  },
  transcriptDraft: {
    borderRadius: 18,
    backgroundColor: '#1a233b',
    borderWidth: 0,
    borderColor: 'transparent',
    padding: 16,
    gap: 6,
  },
  transcriptLabel: {
    color: '#92abd8',
    fontSize: 12,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  transcriptText: {
    color: '#f2f6ff',
    fontSize: 15,
    lineHeight: 22,
  },
  voiceBanner: {
    borderRadius: 24,
    backgroundColor: '#0f2a34',
    borderWidth: 1,
    borderColor: '#24526a',
    paddingHorizontal: 16,
    paddingVertical: 14,
    gap: 6,
    marginBottom: 2,
  },
  voiceBannerError: {
    backgroundColor: '#35161d',
    borderColor: '#683441',
  },
  voiceBannerTitle: {
    color: '#8fdaf6',
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  voiceBannerText: {
    color: '#f4fbff',
    lineHeight: 20,
  },
  voiceErrorCard: {
    borderRadius: 18,
    backgroundColor: '#35161d',
    borderWidth: 0,
    borderColor: 'transparent',
    padding: 16,
    gap: 5,
  },
  voiceErrorTitle: {
    color: '#ffbdc6',
    fontWeight: '800',
  },
  voiceErrorText: {
    color: '#ffe8ec',
    lineHeight: 20,
  },
  centeredConversationBlock: {
    width: '100%',
    maxWidth: 980,
    alignSelf: 'center',
  },
  transcriptScroll: {
    flex: 1,
    borderRadius: 28,
    backgroundColor: '#0d1527',
    borderWidth: 0,
    borderColor: 'transparent',
  },
  transcriptScrollDraftStage: {
    flexGrow: 0,
    flexShrink: 0,
    flexBasis: 'auto',
    backgroundColor: 'transparent',
    borderRadius: 0,
  },
  transcriptContent: {
    padding: 18,
    gap: 12,
  },
  transcriptContentDraftStage: {
    paddingHorizontal: 0,
    paddingVertical: 0,
    gap: 0,
  },
  messageBubble: {
    borderRadius: 0,
    padding: 15,
    gap: 8,
  },
  messageBubbleUser: {
    alignSelf: 'flex-end',
    maxWidth: '78%',
    backgroundColor: '#d4ff65',
    borderRadius: 22,
  },
  messageBubbleAssistant: {
    alignSelf: 'stretch',
    backgroundColor: 'transparent',
    borderWidth: 0,
    paddingHorizontal: 0,
    paddingVertical: 0,
  },
  messageBubbleSystem: {
    alignSelf: 'stretch',
    backgroundColor: '#2a1d3e',
    borderWidth: 1,
    borderColor: '#4d356d',
  },
  messageBubblePending: {
    opacity: 0.76,
  },
  messageBubbleDraft: {
    borderStyle: 'dashed',
  },
  messageHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 16,
  },
  messageLabel: {
    color: '#7d94bf',
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  messageLabelOnLight: {
    color: '#163017',
  },
  messageTime: {
    color: '#7d94bf',
    fontSize: 11,
  },
  messageTimeOnLight: {
    color: '#284525',
  },
  messageText: {
    color: '#f4f8ff',
    fontSize: 15,
    lineHeight: 22,
  },
  messageTextOnLight: {
    color: '#06130b',
  },
  composerDock: {
    width: '100%',
    alignItems: 'center',
    paddingHorizontal: 28,
    paddingTop: 2,
    paddingBottom: 6,
  },
  composerDockDraftStage: {
    paddingTop: 0,
    paddingBottom: 0,
  },
  composerShell: {
    position: 'relative',
    overflow: 'visible',
    width: '100%',
    maxWidth: 980,
    alignSelf: 'center',
    borderRadius: 30,
    backgroundColor: '#10182c',
    borderWidth: 0,
    borderColor: 'transparent',
    paddingHorizontal: 18,
    paddingTop: 14,
    paddingBottom: 12,
    gap: 10,
    shadowColor: '#02060f',
    shadowOpacity: 0.24,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 14 },
    elevation: 14,
  },
  composerShellDraftStage: {
    paddingBottom: 0,
    gap: 8,
  },
  composerUtilityAnchor: {
    position: 'relative',
    zIndex: 20,
  },
  composerTextRegion: {
    position: 'relative',
    minHeight: 0,
    justifyContent: 'flex-start',
    gap: 10,
    width: '100%',
  },
  composerInputMeasureShell: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    opacity: 0,
    pointerEvents: 'none',
    zIndex: -1,
  },
  composerInputMeasureText: {
    width: '100%',
    minHeight: COMPOSER_MIN_HEIGHT,
    color: 'transparent',
    fontSize: 15,
    lineHeight: COMPOSER_LINE_HEIGHT,
    paddingHorizontal: 0,
    paddingVertical: 0,
    ...(Platform.OS === 'web'
      ? ({
          whiteSpace: 'pre-wrap',
          overflowWrap: 'anywhere',
        } as any)
      : null),
  },
  composerHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  composerUtilityRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'stretch',
    gap: 12,
    flexWrap: 'wrap',
  },
  composerTitle: {
    color: '#ffffff',
    fontSize: 17,
    fontWeight: '800',
  },
  composerStatus: {
    color: '#98b0d9',
    fontSize: 13,
    flexShrink: 1,
    textAlign: 'right',
  },
  syntheticThinkingRow: {
    alignSelf: 'stretch',
    paddingVertical: 6,
  },
  syntheticThinkingTextWrap: {
    alignSelf: 'flex-start',
    overflow: 'hidden',
    position: 'relative',
    minWidth: 78,
    minHeight: 20,
    justifyContent: 'center',
  },
  syntheticThinkingHighlightMask: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: 68,
    overflow: 'hidden',
    justifyContent: 'center',
  },
  syntheticThinkingText: {
    color: '#98b0d9',
    fontSize: 13,
    lineHeight: 16,
    fontWeight: '900',
    letterSpacing: 0.2,
  },
  syntheticThinkingTextHighlight: {
    color: '#d4ff65',
    opacity: 0.92,
    textShadowColor: 'rgba(212, 255, 101, 0.34)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 12,
  },
  pendingSwitchCard: {
    borderRadius: 0,
    backgroundColor: '#17243d',
    borderWidth: 1,
    borderColor: '#45648d',
    padding: 14,
    gap: 12,
  },
  pendingSwitchCopy: {
    gap: 4,
  },
  pendingSwitchEyebrow: {
    color: '#8fdaf6',
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 0.9,
    textTransform: 'uppercase',
  },
  pendingSwitchTitle: {
    color: '#f7fbff',
    fontSize: 16,
    fontWeight: '900',
  },
  pendingSwitchText: {
    color: '#c2d3ee',
    fontSize: 13,
    lineHeight: 18,
  },
  pendingSwitchActions: {
    flexDirection: 'row',
    gap: 10,
    flexWrap: 'wrap',
  },
  pendingSwitchPrimaryAction: {
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: '#d4ff65',
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  pendingSwitchPrimaryActionText: {
    color: '#0b1325',
    fontWeight: '900',
  },
  pendingSwitchSecondaryAction: {
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: '#1a2a47',
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  pendingSwitchSecondaryActionText: {
    color: '#e6f0ff',
    fontWeight: '900',
  },
  queuedComposerStack: {
    gap: 8,
  },
  queuedComposerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: '#0c1427',
    borderWidth: 0,
    borderColor: 'transparent',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  queuedComposerText: {
    flex: 1,
    color: '#dce7ff',
    fontSize: 13,
  },
  queuedComposerAction: {
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: '#17253f',
  },
  queuedComposerActionText: {
    color: '#9fe8ff',
    fontSize: 11,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  commandPanel: {
    borderRadius: 14,
    backgroundColor: '#091225',
    borderWidth: 1,
    borderColor: '#2a3f68',
    padding: 12,
    gap: 12,
  },
  commandPanelSlim: {
    width: '100%',
    maxWidth: 560,
    alignSelf: 'flex-start',
  },
  commandPanelFloatingLayer: {
    position: 'absolute',
    bottom: '100%',
    marginBottom: 12,
    zIndex: 30,
  },
  commandPanelFloatingLeft: {
    left: 0,
  },
  commandPanelFloatingRight: {
    right: 0,
  },
  commandPanelFloatingTools: {
    left: 0,
    width: 460,
    maxWidth: '92%',
  },
  commandPanelFloatingPermissions: {
    left: 42,
    width: 430,
    maxWidth: '92%',
  },
  commandPanelFloatingModel: {
    right: 54,
    width: 560,
    maxWidth: '92%',
  },
  commandPanelFloatingBelowRight: {
    top: '100%',
    right: 0,
    bottom: 'auto',
    marginTop: 12,
    marginBottom: 0,
  },
  commandPanelFloating: {
    shadowColor: '#02060f',
    shadowOpacity: 0.42,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 16 },
    elevation: 18,
  },
  toolPackCommandPanel: {
    maxWidth: 460,
    gap: 10,
  },
  permissionCommandPanel: {
    maxWidth: 440,
  },
  permissionOptionList: {
    gap: 4,
  },
  permissionOptionRow: {
    minHeight: 34,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    borderWidth: 0,
    borderColor: 'transparent',
    backgroundColor: '#0d172b',
  },
  permissionOptionRowActive: {
    backgroundColor: '#111f31',
  },
  permissionOptionSelect: {
    minHeight: 32,
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    paddingLeft: 10,
    paddingRight: 2,
    paddingVertical: 5,
  },
  permissionOptionSelectHovered: {
    backgroundColor: 'rgba(255, 255, 255, 0.035)',
  },
  permissionOptionDisabled: {
    opacity: 0.58,
  },
  permissionOptionTitle: {
    flex: 1,
    color: '#edf4ff',
    fontSize: 12,
    fontWeight: '800',
  },
  permissionOptionTitleActive: {
    color: '#d4ff65',
  },
  permissionOptionMeta: {
    color: '#7aa4ff',
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  permissionOptionMetaActive: {
    color: '#d4ff65',
  },
  permissionInfoButton: {
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
    borderTopRightRadius: DESKTOP_RECT_BUTTON_RADIUS,
    borderBottomRightRadius: DESKTOP_RECT_BUTTON_RADIUS,
  },
  permissionInfoButtonActive: {
    backgroundColor: 'rgba(122, 164, 255, 0.1)',
  },
  permissionInfoIcon: {
    color: '#8299bf',
    fontSize: 15,
  },
  permissionInfoBubble: {
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    borderWidth: 0,
    borderColor: 'transparent',
    backgroundColor: '#0d172b',
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 3,
  },
  permissionInfoTitle: {
    color: '#d4ff65',
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  permissionInfoText: {
    color: '#a9bcda',
    fontSize: 12,
    lineHeight: 17,
  },
  draftChoiceCommandPanel: {
    width: 348,
    maxWidth: 348,
    gap: 8,
  },
  draftChoiceSearchShell: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderRadius: 12,
    backgroundColor: '#2f2f2f',
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  draftChoiceSearchGlyph: {
    color: '#9b9b9b',
    fontSize: 13,
  },
  draftChoiceSearchInput: {
    flex: 1,
    color: '#f5f5f5',
    fontSize: 14,
    paddingVertical: 0,
  },
  draftChoiceSectionLabel: {
    color: '#8f8f8f',
    fontSize: 11,
    fontWeight: '700',
    paddingHorizontal: 4,
  },
  draftChoiceScroll: {
    maxHeight: 152,
  },
  draftChoiceList: {
    gap: 2,
  },
  draftChoiceRow: {
    minHeight: 32,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: 'transparent',
  },
  draftChoiceRowHovered: {
    backgroundColor: '#3a3a3a',
  },
  draftChoiceRowSelected: {
    backgroundColor: '#474747',
  },
  draftChoiceRowIcon: {
    color: '#b4bccb',
    fontSize: 14,
  },
  draftChoiceRowIconSelected: {
    color: '#eef4ff',
  },
  draftChoiceRowCopy: {
    flex: 1,
    minWidth: 0,
  },
  draftChoiceRowTitle: {
    flex: 1,
    color: '#e8ebf2',
    fontSize: 13,
    fontWeight: '700',
  },
  draftChoiceRowSubtitle: {
    color: '#8b98ad',
    fontSize: 11,
    marginTop: 2,
  },
  draftChoiceRowTitleSelected: {
    color: '#ffffff',
  },
  draftChoiceRowCheck: {
    color: '#eef4ff',
    fontSize: 13,
  },
  draftChoiceFooter: {
    borderTopWidth: 1,
    borderTopColor: '#252525',
    paddingTop: 8,
  },
  draftChoiceFooterAction: {
    minHeight: 32,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  draftChoiceFooterActionHovered: {
    backgroundColor: '#323232',
  },
  draftChoiceFooterActionIcon: {
    color: '#d9e5fb',
    fontSize: 14,
  },
  draftChoiceFooterActionText: {
    color: '#f4f8ff',
    fontSize: 13,
    fontWeight: '700',
  },
  commandPanelHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  commandPanelHeaderCopy: {
    flex: 1,
    minWidth: 0,
    gap: 3,
  },
  commandPanelHeaderLine: {
    minHeight: 28,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  commandPanelCompactTitle: {
    color: '#f7fbff',
    fontSize: 13,
    fontWeight: '900',
    letterSpacing: 0.2,
  },
  commandPanelInfoButton: {
    width: 20,
    height: 20,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
  },
  commandPanelInfoIcon: {
    color: '#a9bcda',
    fontSize: 12,
    lineHeight: 13,
    fontWeight: '900',
  },
  commandPanelEyebrow: {
    color: '#d4ff65',
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  commandPanelTitle: {
    color: '#f7fbff',
    fontSize: 17,
    fontWeight: '900',
  },
  commandPanelText: {
    color: '#a9bcda',
    fontSize: 13,
    lineHeight: 18,
  },
  commandPanelWarningText: {
    color: '#d4ff65',
    fontSize: 12,
    lineHeight: 17,
  },
  commandPanelCloseButton: {
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: '#17253f',
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  commandPanelCloseText: {
    color: '#dbe7fb',
    fontWeight: '900',
    fontSize: 12,
  },
  modelPickerScroll: {
    maxHeight: 220,
  },
  modelPickerContent: {
    gap: 10,
  },
  modelPickerSection: {
    gap: 7,
  },
  modelPickerSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  modelPickerSectionTitle: {
    color: '#d4ff65',
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  modelPickerSectionMeta: {
    flexShrink: 1,
    color: '#8ca3c7',
    fontSize: 11,
    fontWeight: '700',
  },
  modelProviderBlock: {
    gap: 6,
  },
  modelProviderTitle: {
    color: '#7aa4ff',
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  modelProviderCaption: {
    color: '#94a9cc',
    fontSize: 12,
    lineHeight: 17,
  },
  modelProviderDropdownList: {
    gap: 5,
  },
  modelProviderDropdown: {
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    borderWidth: 0,
    borderColor: 'transparent',
    backgroundColor: '#0d172b',
    overflow: 'hidden',
  },
  modelProviderDropdownHeader: {
    minHeight: 36,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  modelProviderDropdownHeaderHovered: {
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
  },
  modelProviderDropdownHeaderActive: {
    backgroundColor: 'rgba(212, 255, 101, 0.08)',
  },
  modelProviderDropdownCopy: {
    flex: 1,
    minWidth: 0,
  },
  modelProviderDropdownTitle: {
    color: '#edf4ff',
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 0.7,
    textTransform: 'uppercase',
  },
  modelProviderDropdownMeta: {
    color: '#8da4c8',
    fontSize: 11,
    marginTop: 2,
  },
  modelProviderDropdownChevron: {
    color: '#8da4c8',
    fontSize: 12,
  },
  modelProviderDropdownBody: {
    borderTopWidth: 0,
    borderTopColor: 'transparent',
    paddingTop: 2,
    paddingRight: 5,
    paddingBottom: 5,
    paddingLeft: 16,
    gap: 4,
  },
  composerAttachmentSection: {
    gap: 7,
  },
  composerAttachmentAction: {
    minHeight: 32,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: '#0d172b',
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  composerAttachmentActionHovered: {
    backgroundColor: '#13223e',
  },
  composerAttachmentActionDisabled: {
    opacity: 0.56,
  },
  composerAttachmentIcon: {
    width: 18,
    color: '#8ca3c7',
    fontSize: 17,
    lineHeight: 18,
    fontWeight: '500',
    textAlign: 'center',
  },
  composerAttachmentActionTitle: {
    flex: 1,
    color: '#edf4ff',
    fontSize: 12,
    fontWeight: '900',
  },
  toolPackCompactList: {
    gap: 6,
  },
  toolPackCompactGroup: {
    gap: 6,
  },
  toolPackCompactRow: {
    minHeight: 38,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    backgroundColor: '#0f182d',
    borderWidth: 0,
    borderColor: 'transparent',
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  toolPackCompactRowEnabled: {
    backgroundColor: '#10182c',
  },
  toolPackCompactRowUnavailable: {
    opacity: 0.64,
  },
  toolPackCompactLabel: {
    flex: 1,
    color: '#d9e5fb',
    fontSize: 13,
    fontWeight: '800',
  },
  toolPackCompactLabelEnabled: {
    color: '#d4ff65',
  },
  toolPackCompactLabelUnavailable: {
    color: '#93a5c6',
  },
  toolPackCompactActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  toolPackInfoButton: {
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
  },
  toolPackInfoButtonHovered: {
    backgroundColor: '#13223e',
  },
  toolPackInfoButtonActive: {
    backgroundColor: '#162844',
  },
  toolPackInfoIcon: {
    color: '#7f97bd',
    fontSize: 13,
  },
  toolPackInfoIconActive: {
    color: '#d4ff65',
  },
  toolPackInfoBubble: {
    backgroundColor: '#111c33',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 4,
  },
  toolPackInfoFloatingBubble: {
    position: 'absolute',
    width: 292,
    backgroundColor: '#111c33',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 4,
    shadowColor: '#02060f',
    shadowOpacity: 0.36,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 18,
    zIndex: 40,
  },
  toolPackInfoTitle: {
    color: '#f4f8ff',
    fontSize: 12,
    fontWeight: '900',
  },
  toolPackInfoText: {
    color: '#9cb1d4',
    fontSize: 12,
    lineHeight: 17,
  },
  toolPackInfoWarning: {
    color: '#d4ff65',
    fontSize: 11,
    lineHeight: 16,
  },
  toolPackSwitch: {
    width: 42,
    height: 24,
    borderRadius: 999,
    backgroundColor: '#202b43',
    padding: 3,
    justifyContent: 'center',
  },
  toolPackSwitchActive: {
    backgroundColor: '#d4ff65',
  },
  toolPackSwitchSaving: {
    opacity: 0.72,
  },
  toolPackSwitchDisabled: {
    backgroundColor: '#1a2235',
  },
  toolPackSwitchKnob: {
    width: 18,
    height: 18,
    borderRadius: 999,
    backgroundColor: '#f4f8ff',
  },
  toolPackSwitchKnobActive: {
    alignSelf: 'flex-end',
    backgroundColor: '#0b1325',
  },
  modelList: {
    gap: 6,
  },
  modelListItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: 'transparent',
    borderWidth: 0,
    borderColor: 'transparent',
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  modelAutoListItem: {
    minHeight: 34,
    backgroundColor: '#0d172b',
  },
  modelNestedListItem: {
    minHeight: 32,
    paddingLeft: 12,
    paddingRight: 8,
    paddingVertical: 5,
  },
  modelListItemHovered: {
    backgroundColor: '#13223e',
  },
  modelListItemActive: {
    backgroundColor: '#d4ff65',
  },
  toolPackListItemActive: {
    backgroundColor: '#101b32',
    borderColor: '#2f567e',
  },
  modelListItemDisabled: {
    opacity: 0.52,
  },
  modelListItemCopy: {
    flex: 1,
  },
  modelListItemTitle: {
    color: '#f4f8ff',
    fontWeight: '900',
    fontSize: 13,
  },
  modelListItemTitleActive: {
    color: '#0b1325',
  },
  toolPackListItemTitleActive: {
    color: '#d4ff65',
  },
  modelListItemMeta: {
    color: '#7aa4ff',
    fontSize: 10,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  modelListItemMetaActive: {
    color: '#193214',
  },
  toolPackListItemMetaActive: {
    color: '#d4ff65',
  },
  modelListItemMetaDisabled: {
    color: '#8b99b5',
  },
  toolPackListItemCaptionActive: {
    color: '#b7d88f',
  },
  timelineTranscriptCard: {
    alignSelf: 'stretch',
    borderRadius: 18,
    backgroundColor: '#101a30',
    borderWidth: 1,
    borderColor: '#203657',
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 8,
  },
  timelineTranscriptCardAccent: {
    borderColor: '#2f567e',
    backgroundColor: '#10203b',
  },
  timelineTranscriptCardWarn: {
    borderColor: '#78561d',
    backgroundColor: '#231808',
  },
  timelineTranscriptCardError: {
    borderColor: '#78445a',
    backgroundColor: '#27131a',
  },
  timelineTranscriptHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  timelineTranscriptEyebrow: {
    color: '#9fc7ff',
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  timelineTranscriptTime: {
    color: '#7d94bf',
    fontSize: 11,
  },
  timelineTranscriptBody: {
    color: '#eef4ff',
    fontSize: 14,
    lineHeight: 21,
  },
  timelineTranscriptResultBlock: {
    gap: 4,
    borderTopWidth: 1,
    borderTopColor: '#203657',
    paddingTop: 8,
  },
  timelineTranscriptResultEyebrow: {
    color: '#8fe0ff',
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  timelineTranscriptResultText: {
    color: '#d4e3ff',
    fontSize: 13,
    lineHeight: 19,
  },
  commandPanelEmpty: {
    borderRadius: 12,
    backgroundColor: '#101b32',
    padding: 12,
    gap: 4,
  },
  commandPanelEmptyTitle: {
    color: '#f7fbff',
    fontWeight: '900',
  },
  commandPanelEmptyText: {
    color: '#a9bcda',
    lineHeight: 18,
  },
  commandPanelActionRow: {
    flexDirection: 'row',
    gap: 10,
    flexWrap: 'wrap',
  },
  commandPanelPrimaryAction: {
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: '#d4ff65',
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  commandPanelPrimaryActionActive: {
    backgroundColor: '#97f46f',
  },
  commandPanelPrimaryActionText: {
    color: '#0b1325',
    fontWeight: '900',
  },
});
