import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  shell: {
    borderRadius: 26,
    backgroundColor: '#111111',
    borderWidth: 1,
    borderColor: '#252525',
    padding: 20,
    gap: 18,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 18,
  },
  headerCopy: {
    flex: 1,
    gap: 6,
  },
  eyebrow: {
    color: '#848484',
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.9,
  },
  title: {
    color: '#f3f3f3',
    fontSize: 24,
    fontWeight: '800',
  },
  subtitle: {
    color: '#989898',
    fontSize: 13,
    lineHeight: 20,
    maxWidth: 760,
  },
  versionBadge: {
    width: 188,
    backgroundColor: '#181818',
    borderWidth: 1,
    borderColor: '#262626',
    borderRadius: 18,
    padding: 14,
    gap: 4,
  },
  versionLabel: {
    color: '#7f7f7f',
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  versionValue: {
    color: '#f3f3f3',
    fontSize: 18,
    fontWeight: '800',
  },
  settingsFrame: {
    flexDirection: 'row',
    gap: 18,
    minHeight: 640,
  },
  settingsSidebar: {
    width: 260,
    backgroundColor: '#161616',
    borderWidth: 1,
    borderColor: '#252525',
    borderRadius: 20,
    padding: 14,
    gap: 14,
  },
  backToAppButton: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 14,
    backgroundColor: '#1b1b1b',
  },
  backToAppButtonText: {
    color: '#d8d8d8',
    fontSize: 13,
    fontWeight: '700',
  },
  backToAppPlaceholder: {
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  backToAppPlaceholderText: {
    color: '#8e8e8e',
    fontSize: 13,
    fontWeight: '700',
  },
  settingsNavList: {
    gap: 8,
  },
  settingsNavItem: {
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 12,
    gap: 3,
  },
  settingsNavItemActive: {
    backgroundColor: '#242424',
  },
  settingsNavItemTitle: {
    color: '#e5e5e5',
    fontSize: 14,
    fontWeight: '700',
  },
  settingsNavItemTitleActive: {
    color: '#ffffff',
  },
  settingsNavItemDescription: {
    color: '#7b7b7b',
    fontSize: 11,
    lineHeight: 15,
  },
  settingsContentPane: {
    flex: 1,
    backgroundColor: '#151515',
    borderWidth: 1,
    borderColor: '#252525',
    borderRadius: 20,
    overflow: 'hidden',
  },
  settingsContentHeader: {
    paddingHorizontal: 24,
    paddingTop: 22,
    paddingBottom: 18,
    borderBottomWidth: 1,
    borderBottomColor: '#242424',
  },
  settingsContentHeaderCopy: {
    gap: 4,
  },
  settingsContentTitle: {
    color: '#f5f5f5',
    fontSize: 22,
    fontWeight: '800',
  },
  settingsContentSubtitle: {
    color: '#8f8f8f',
    fontSize: 13,
  },
  formScroll: {
    flex: 1,
    maxHeight: 620,
  },
  formContent: {
    gap: 16,
    paddingHorizontal: 24,
    paddingTop: 20,
    paddingBottom: 24,
  },
  warningCard: {
    borderRadius: 18,
    backgroundColor: '#2a1719',
    borderWidth: 1,
    borderColor: '#553138',
    padding: 16,
    gap: 8,
  },
  warningTitle: {
    color: '#ffd7dd',
    fontWeight: '800',
  },
  warningLine: {
    color: '#ffecef',
    lineHeight: 20,
  },
  section: {
    borderRadius: 18,
    backgroundColor: '#1a1a1a',
    borderWidth: 1,
    borderColor: '#282828',
    padding: 16,
    gap: 10,
  },
  sectionTitle: {
    color: '#f0f0f0',
    fontSize: 18,
    fontWeight: '800',
  },
  helperText: {
    color: '#989898',
    lineHeight: 20,
  },
  settingStack: {
    gap: 10,
  },
  settingCard: {
    borderRadius: 16,
    backgroundColor: '#121212',
    borderWidth: 1,
    borderColor: '#282828',
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 10,
  },
  settingCardInner: {
    borderRadius: 12,
    backgroundColor: '#171717',
    borderWidth: 1,
    borderColor: '#303030',
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 8,
  },
  settingCardTitle: {
    color: '#f2f2f2',
    fontSize: 14,
    fontWeight: '800',
  },
  settingCardDescription: {
    color: '#9a9a9a',
    fontSize: 12,
    lineHeight: 18,
  },
  settingActionRow: {
    flexDirection: 'row',
    gap: 10,
    flexWrap: 'wrap',
    alignItems: 'center',
  },
  fieldBlock: {
    gap: 6,
  },
  fieldLabel: {
    color: '#dfdfdf',
    fontSize: 13,
    fontWeight: '700',
  },
  fieldLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  infoBadge: {
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#3a4f72',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#111a2a',
  },
  infoBadgeText: {
    color: '#9ebcff',
    fontSize: 10,
    fontWeight: '900',
    lineHeight: 12,
  },
  input: {
    borderRadius: 14,
    backgroundColor: '#111111',
    borderWidth: 1,
    borderColor: '#3a3a3a',
    color: '#f6f6f6',
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  inputDisabled: {
    backgroundColor: '#181818',
    borderColor: '#2a2a2a',
    color: '#9f9f9f',
  },
  vaultCredentialBlock: {
    gap: 8,
    paddingTop: 6,
  },
  vaultCredentialRow: {
    flexDirection: 'row',
    gap: 10,
    flexWrap: 'wrap',
    alignItems: 'center',
  },
  vaultCredentialInput: {
    flex: 1,
    minWidth: 220,
  },
  telegramUserList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    minHeight: 32,
    alignItems: 'center',
  },
  telegramUserChip: {
    borderRadius: 999,
    backgroundColor: '#203654',
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  telegramUserChipText: {
    color: '#f4f8ff',
    fontSize: 12,
    fontWeight: '800',
  },
  telegramUserInput: {
    minWidth: 220,
  },
  numberInput: {
    width: 74,
    textAlign: 'center',
    paddingHorizontal: 10,
  },
  memoryEditor: {
    minHeight: 240,
    lineHeight: 20,
  },
  sharedPromptInput: {
    minHeight: 120,
    lineHeight: 20,
  },
  validationText: {
    fontSize: 12,
    lineHeight: 17,
  },
  validationTextChecking: {
    color: '#8fb4dc',
  },
  validationTextValid: {
    color: '#9cf0b7',
  },
  validationTextInvalid: {
    color: '#ffb2a4',
  },
  validationTextError: {
    color: '#ffd27a',
  },
  settingRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 16,
    paddingVertical: 6,
  },
  settingRowCopy: {
    flex: 1,
    gap: 4,
  },
  settingRowTitle: {
    color: '#f0f0f0',
    fontSize: 14,
    fontWeight: '700',
  },
  settingRowDescription: {
    color: '#8f8f8f',
    fontSize: 12,
    lineHeight: 18,
  },
  settingRowControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  sleepModeCard: {
    borderRadius: 16,
    backgroundColor: '#121212',
    borderWidth: 1,
    borderColor: '#282828',
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 12,
  },
  sleepModeStatusBadge: {
    borderRadius: 999,
    backgroundColor: '#252525',
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  sleepModeStatusActive: {
    backgroundColor: '#203654',
  },
  sleepModeStatusText: {
    color: '#f4f8ff',
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  sleepModeActionRow: {
    flexDirection: 'row',
    gap: 10,
    flexWrap: 'wrap',
  },
  sleepModeActionButton: {
    borderRadius: 12,
    backgroundColor: '#efefef',
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  sleepModeActionButtonActive: {
    backgroundColor: '#d4ff65',
  },
  sleepModeActionButtonText: {
    color: '#111111',
    fontWeight: '800',
    fontSize: 12,
  },
  sleepModeActionButtonTextActive: {
    color: '#081324',
  },
  sleepModeSecondaryButton: {
    borderRadius: 12,
    backgroundColor: '#1f1f1f',
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  sleepModeSecondaryButtonText: {
    color: '#e2e2e2',
    fontWeight: '800',
    fontSize: 12,
  },
  sleepModeConfirmPanel: {
    borderRadius: 14,
    backgroundColor: '#241a12',
    borderWidth: 1,
    borderColor: '#5a3a1e',
    padding: 12,
    gap: 8,
  },
  sleepModeConfirmTitle: {
    color: '#ffe2bf',
    fontWeight: '800',
  },
  sleepModeConfirmText: {
    color: '#f4d6b5',
    lineHeight: 19,
  },
  sleepModeConfirmButton: {
    alignSelf: 'flex-start',
    borderRadius: 12,
    backgroundColor: '#ffcf7a',
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  sleepModeConfirmButtonText: {
    color: '#17100a',
    fontWeight: '800',
    fontSize: 12,
  },
  stepperControl: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  stepperButton: {
    width: 34,
    height: 34,
    borderRadius: 12,
    backgroundColor: '#232323',
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepperButtonText: {
    color: '#f3f3f3',
    fontSize: 18,
    fontWeight: '800',
  },
  compactActionButton: {
    borderRadius: 12,
    backgroundColor: '#2f2f2f',
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  compactActionButtonText: {
    color: '#f0f0f0',
    fontWeight: '800',
    fontSize: 12,
  },
  toggleSwitch: {
    width: 52,
    height: 30,
    borderRadius: 999,
    backgroundColor: '#2d2d2d',
    padding: 4,
    justifyContent: 'center',
  },
  toggleSwitchActive: {
    backgroundColor: '#53a4ff',
  },
  toggleSwitchKnob: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#f3f3f3',
  },
  toggleSwitchKnobActive: {
    alignSelf: 'flex-end',
  },
  pathValue: {
    color: '#dadada',
    lineHeight: 20,
  },
  pathActions: {
    flexDirection: 'row',
    gap: 10,
    flexWrap: 'wrap',
  },
  pathButton: {
    borderRadius: 12,
    backgroundColor: '#efefef',
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  pathButtonText: {
    color: '#101010',
    fontWeight: '800',
  },
  buttonDisabled: {
    opacity: 0.55,
  },
  providerRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  providerChip: {
    borderRadius: 999,
    backgroundColor: '#262626',
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  providerChipText: {
    color: '#cdcdcd',
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  providerVaultStatus: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#2c3a2c',
    backgroundColor: '#151d15',
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    flexWrap: 'wrap',
  },
  providerVaultStatusText: {
    color: '#cce8ca',
    fontSize: 12,
    fontWeight: '700',
  },
  providerVaultDeleteButton: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#5b2b2b',
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  providerVaultDeleteText: {
    color: '#ffb5b5',
    fontSize: 11,
    fontWeight: '800',
  },
  noteCard: {
    borderRadius: 16,
    backgroundColor: '#121212',
    borderWidth: 1,
    borderColor: '#242424',
    padding: 14,
    gap: 6,
  },
  noteLine: {
    color: '#d7d7d7',
    lineHeight: 20,
  },
  noteLineWithInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
  },
  pairingQrCard: {
    borderRadius: 18,
    backgroundColor: '#101010',
    borderWidth: 1,
    borderColor: '#2f3f56',
    padding: 14,
    gap: 14,
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  pairingQrCopy: {
    flex: 1,
    minWidth: 220,
    gap: 6,
  },
  pairingQrTitle: {
    color: '#f4f8ff',
    fontSize: 16,
    fontWeight: '800',
  },
  voiceModeRow: {
    flexDirection: 'row',
    gap: 10,
    flexWrap: 'wrap',
  },
  voiceModeButton: {
    borderRadius: 12,
    backgroundColor: '#121212',
    borderWidth: 1,
    borderColor: '#282828',
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  voiceModeButtonActive: {
    backgroundColor: '#d4ff65',
    borderColor: '#d4ff65',
  },
  voiceModeButtonDisabled: {
    opacity: 0.45,
  },
  voiceModeButtonText: {
    color: '#dfdfdf',
    fontWeight: '800',
  },
  voiceModeButtonTextActive: {
    color: '#081324',
  },
  voiceModeHelper: {
    color: '#969696',
    lineHeight: 18,
  },
  voicePackList: {
    gap: 10,
  },
  voicePackCard: {
    borderRadius: 16,
    backgroundColor: '#121212',
    borderWidth: 1,
    borderColor: '#242424',
    padding: 14,
    gap: 10,
  },
  voicePackHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  voicePackCopy: {
    flex: 1,
    gap: 4,
  },
  voicePackTitle: {
    color: '#f2f2f2',
    fontWeight: '800',
  },
  voicePackDescription: {
    color: '#b6b6b6',
    lineHeight: 18,
  },
  voicePackStatusBadge: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    alignSelf: 'flex-start',
  },
  voicePackStatusReady: {
    backgroundColor: '#203654',
  },
  voicePackStatusPlaceholder: {
    backgroundColor: '#353535',
  },
  voicePackStatusText: {
    color: '#f4f8ff',
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  voicePackMeta: {
    color: '#d7d7d7',
    lineHeight: 19,
  },
  voicePackProgressCard: {
    gap: 8,
    borderRadius: 14,
    backgroundColor: '#171717',
    borderWidth: 1,
    borderColor: '#2b2b2b',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  voicePackProgressTitle: {
    color: '#efefef',
    fontWeight: '700',
  },
  voicePackProgressTrack: {
    height: 8,
    borderRadius: 999,
    overflow: 'hidden',
    backgroundColor: '#242424',
  },
  voicePackProgressFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: '#9bf24c',
  },
  voicePackProgressMeta: {
    color: '#9b9b9b',
    fontSize: 12,
    textTransform: 'capitalize',
  },
  voicePackActionRow: {
    flexDirection: 'row',
    gap: 10,
    flexWrap: 'wrap',
    alignItems: 'center',
  },
  voicePackActionButton: {
    borderRadius: 12,
    backgroundColor: '#efefef',
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  voicePackActionButtonSecondary: {
    borderRadius: 12,
    backgroundColor: '#1f1f1f',
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  dangerOutlineButton: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#ef4444',
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  voicePackActionText: {
    color: '#111111',
    fontWeight: '800',
  },
  voicePackActionTextSecondary: {
    color: '#e2e2e2',
    fontWeight: '800',
  },
  dangerOutlineText: {
    color: '#fecaca',
    fontWeight: '800',
  },
  metaRow: {
    flexDirection: 'row',
    gap: 10,
    flexWrap: 'wrap',
  },
  metaCard: {
    flex: 1,
    minWidth: 190,
    borderRadius: 16,
    backgroundColor: '#121212',
    borderWidth: 1,
    borderColor: '#242424',
    padding: 14,
    gap: 4,
  },
  metaLabel: {
    color: '#8f8f8f',
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  metaValue: {
    color: '#f4f4f4',
    lineHeight: 20,
    fontWeight: '700',
  },
  valueWithInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
  },
  metaIssue: {
    color: '#ffb3a6',
    fontSize: 12,
    lineHeight: 17,
  },
  metaIssueRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
  },
  extensionGuideCard: {
    borderRadius: 16,
    backgroundColor: '#121212',
    borderWidth: 1,
    borderColor: '#242424',
    padding: 14,
    gap: 6,
  },
  extensionGuideTitle: {
    color: '#f2f2f2',
    fontWeight: '800',
  },
  extensionGuideStep: {
    color: '#d7d7d7',
    lineHeight: 20,
  },
  extensionActionRow: {
    flexDirection: 'row',
    gap: 10,
    flexWrap: 'wrap',
  },
  footer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  secondaryButton: {
    borderRadius: 14,
    backgroundColor: '#1e1e1e',
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  secondaryButtonText: {
    color: '#d9d9d9',
    fontWeight: '800',
  },
  primaryButton: {
    borderRadius: 14,
    backgroundColor: '#d4ff65',
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  primaryButtonDisabled: {
    opacity: 0.7,
  },
  primaryButtonText: {
    color: '#081324',
    fontWeight: '800',
  },
});
