import { Platform, StyleSheet } from 'react-native';

import { DESKTOP_RECT_BUTTON_RADIUS } from './desktopUiTokens';
import { COMPOSER_LINE_HEIGHT, COMPOSER_MAX_HEIGHT, COMPOSER_MIN_HEIGHT, HUD } from './DesktopConversationView.styleConstants';

export const desktopConversationStylesPart4 = StyleSheet.create({
  commandPanelSecondaryAction: {
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    borderWidth: 1,
    borderColor: '#355178',
    backgroundColor: 'rgba(16, 27, 50, 0.86)',
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  commandPanelSecondaryActionText: {
    color: '#d9e7ff',
    fontWeight: '800',
  },
  interruptOptionList: {
    gap: 8,
  },
  interruptOptionCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: '#101b32',
    borderWidth: 1,
    borderColor: '#213655',
    paddingHorizontal: 12,
    paddingVertical: 11,
  },
  interruptOptionCardActive: {
    backgroundColor: '#172947',
    borderColor: '#62d2ff',
  },
  interruptOptionCopy: {
    flex: 1,
    gap: 3,
  },
  interruptOptionTitle: {
    color: '#f4f8ff',
    fontWeight: '900',
    fontSize: 13,
  },
  interruptOptionTitleActive: {
    color: '#f7fbff',
  },
  interruptOptionText: {
    color: '#a9bcda',
    fontSize: 12,
    lineHeight: 17,
  },
  interruptOptionMeta: {
    color: '#7aa4ff',
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  interruptOptionMetaActive: {
    color: '#62d2ff',
  },
  sessionCommandScroll: {
    maxHeight: 320,
  },
  sessionCommandList: {
    gap: 8,
  },
  sessionCommandCard: {
    borderRadius: 0,
    backgroundColor: '#101b32',
    borderWidth: 1,
    borderColor: '#213659',
    padding: 12,
    gap: 5,
  },
  sessionCommandCardActive: {
    borderColor: '#d4ff65',
    backgroundColor: '#18273b',
  },
  sessionCommandHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
  },
  sessionCommandCopy: {
    flex: 1,
    gap: 3,
  },
  sessionCommandTitle: {
    color: '#f7fbff',
    fontSize: 15,
    fontWeight: '900',
  },
  sessionCommandMeta: {
    color: '#9fb4d7',
    fontSize: 11,
  },
  sessionCommandBadge: {
    borderRadius: 0,
    backgroundColor: '#d4ff65',
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  sessionCommandBadgeText: {
    color: '#0b1325',
    fontSize: 10,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  sessionCommandPreview: {
    color: '#d7e4f8',
    fontSize: 13,
    lineHeight: 18,
  },
  interruptRow: {
    flexDirection: 'row',
    gap: 10,
    flexWrap: 'wrap',
  },
  composerStatusBar: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'stretch',
    gap: 8,
    flexWrap: 'wrap',
    flex: 1,
    minWidth: 250,
  },
  composerStatusPill: {
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: 'transparent',
    paddingHorizontal: 6,
    paddingVertical: 4,
    justifyContent: 'center',
  },
  composerStatusPillWide: {
    minWidth: 152,
    flexShrink: 1,
  },
  composerStatusPillInteractiveActive: {
    borderColor: 'transparent',
    backgroundColor: 'transparent',
  },
  composerStatusPillLabel: {
    color: '#7f96bc',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  composerStatusPillValue: {
    color: '#f7fbff',
    fontSize: 12,
    fontWeight: '800',
  },
  composerStatusPillMeta: {
    color: '#8da2c4',
    fontSize: 11,
  },
  composerIconButton: {
    width: 32,
    height: 32,
    minWidth: 32,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: 'transparent',
  },
  composerIconButtonHovered: {
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    borderColor: 'rgba(255, 255, 255, 0.08)',
  },
  composerIconButtonActive: {
    backgroundColor: 'rgba(24, 243, 255, 0.1)',
    borderColor: 'rgba(24, 243, 255, 0.2)',
  },
  composerIconButtonGlyph: {
    color: '#9ea7b7',
    fontSize: 24,
    lineHeight: 26,
    fontWeight: '300',
  },
  composerPermissionButton: {
    minHeight: 32,
    maxWidth: 180,
    borderRadius: 999,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 6,
    paddingVertical: 4,
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: 'transparent',
  },
  composerPermissionButtonActive: {
    backgroundColor: 'rgba(255, 130, 54, 0.1)',
    borderColor: 'rgba(255, 130, 54, 0.24)',
  },
  composerPermissionIcon: {
    width: 15,
    height: 15,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#f97316',
    color: '#fb923c',
    fontSize: 10,
    lineHeight: 13,
    fontWeight: '900',
    textAlign: 'center',
  },
  composerPermissionText: {
    color: '#fb923c',
    fontSize: 12,
    fontWeight: '700',
  },
  composerModelButton: {
    minHeight: 32,
    maxWidth: 230,
    borderRadius: 999,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 8,
    paddingVertical: 4,
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: 'transparent',
  },
  composerModelButtonActive: {
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    borderColor: 'rgba(255, 255, 255, 0.12)',
  },
  composerModelText: {
    color: '#e6ebf5',
    fontSize: 12,
    fontWeight: '700',
  },
  composerInlineChevron: {
    color: '#8e96a6',
    fontSize: 12,
  },
  composerStatusContextRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    flexWrap: 'wrap',
  },
  contextMeterButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    paddingHorizontal: 0,
    paddingVertical: 0,
    overflow: 'hidden',
  },
  contextMeterButtonCollapsed: {
    width: 18,
    minWidth: 18,
    height: 18,
  },
  contextMeterButtonExpanded: {
    minWidth: 176,
    paddingHorizontal: 6,
  },
  contextMeterHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  contextMeterState: {
    color: '#d9e7fb',
    fontSize: 11,
    fontWeight: '700',
  },
  contextMeterOrb: {
    position: 'relative',
    width: 18,
    height: 18,
    borderRadius: 999,
    backgroundColor: '#10213b',
    borderWidth: 1,
    borderColor: '#27466d',
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
  },
  contextMeterOrbFill: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#6fd6ff',
  },
  contextMeterOrbFillWarn: {
    backgroundColor: '#d4ff65',
  },
  contextMeterOrbFillCompact: {
    backgroundColor: '#82ffb3',
  },
  contextMeterOrbCore: {
    width: 6,
    height: 6,
    borderRadius: 999,
    backgroundColor: '#eaf4ff',
    opacity: 0.88,
  },
  contextMeterDetail: {
    minWidth: 138,
    gap: 1,
  },
  contextMeterDetailTitle: {
    color: '#dce7ff',
    fontSize: 11,
    fontWeight: '800',
  },
  contextMeterDetailText: {
    color: '#b2c5e4',
    fontSize: 11,
  },
  contextMeterDetailMeta: {
    color: '#7f96bc',
    fontSize: 10,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  composerFooterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  composerFooterControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
    minWidth: 0,
  },
  composerFooterActions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 7,
    flexShrink: 0,
  },
  draftComposerMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
    marginTop: 0,
    overflow: 'visible',
  },
  draftComposerMetaTray: {
    marginTop: 4,
    marginHorizontal: -18,
    marginBottom: -12,
    paddingTop: 6,
    paddingBottom: 10,
    paddingHorizontal: 18,
    borderTopWidth: 1,
    borderTopColor: '#11192b',
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    backgroundColor: '#0a1020',
    overflow: 'visible',
  },
  draftComposerMetaControl: {
    position: 'relative',
    overflow: 'visible',
  },
  draftComposerMetaChip: {
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    minHeight: 30,
    paddingHorizontal: 12,
    paddingVertical: 5,
    backgroundColor: '#111823',
    borderRadius: 12,
  },
  draftComposerMetaChipHovered: {
    backgroundColor: '#1a2230',
  },
  draftComposerMetaChipActive: {
    backgroundColor: '#1c2535',
  },
  draftComposerMetaChipDisabled: {
    opacity: 0.6,
  },
  draftComposerMetaIcon: {
    color: '#b4bccb',
    fontSize: 14,
  },
  draftComposerMetaLabel: {
    maxWidth: 220,
    color: '#edf3ff',
    fontSize: 12,
    fontWeight: '800',
  },
  draftComposerMetaChevronIcon: {
    color: '#aebed8',
    fontSize: 13,
  },
  draftComposerInlineDropdown: {
    position: 'absolute',
    top: '100%',
    left: 0,
    marginTop: 8,
    zIndex: 40,
  },
  composerStatusInline: {
    color: '#8da2c4',
    fontSize: 12,
    maxWidth: 160,
    textAlign: 'right',
  },
  interruptChooserButton: {
    minWidth: 132,
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: 'transparent',
    paddingHorizontal: 12,
    paddingVertical: 9,
    gap: 4,
    alignSelf: 'flex-start',
  },
  interruptChooserButtonActive: {
    borderColor: 'transparent',
    backgroundColor: 'transparent',
  },
  statusSurfaceHovered: {
    backgroundColor: '#0a1427',
    borderColor: 'transparent',
  },
  interruptChooserEyebrow: {
    color: '#7f96bc',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  interruptChooserValue: {
    color: '#f7fbff',
    fontSize: 13,
    fontWeight: '800',
  },
  commandSuggestionMenu: {
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: '#091225',
    borderWidth: 1,
    borderColor: '#2a3f68',
    padding: 8,
    gap: 6,
  },
  commandSuggestionTitle: {
    color: '#7aa4ff',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  commandSuggestionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  commandSuggestionCloseButton: {
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: '#17253f',
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  commandSuggestionCloseText: {
    color: '#dbe7fb',
    fontSize: 11,
    fontWeight: '800',
  },
  commandSuggestionList: {
    gap: 4,
  },
  commandSuggestionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: '#101b32',
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  commandSuggestionCommand: {
    color: '#d4ff65',
    fontWeight: '900',
    minWidth: 110,
  },
  commandSuggestionDescription: {
    color: '#b9c8e6',
    flex: 1,
    fontSize: 13,
  },
  composerRow: {
    flexDirection: 'row',
    gap: 12,
    alignItems: 'flex-end',
  },
  composerInput: {
    width: '100%',
    minHeight: COMPOSER_MIN_HEIGHT,
    maxHeight: COMPOSER_MAX_HEIGHT,
    borderRadius: 0,
    backgroundColor: 'transparent',
    borderWidth: 0,
    borderColor: 'transparent',
    color: '#f6fbff',
    paddingHorizontal: 0,
    paddingVertical: 0,
    paddingTop: 0,
    paddingBottom: 0,
    textAlignVertical: 'top',
    fontSize: 15,
    lineHeight: COMPOSER_LINE_HEIGHT,
    overflow: 'hidden',
  },
  sendButton: {
    borderRadius: 999,
    backgroundColor: '#67d9ff',
    width: 42,
    minWidth: 42,
    height: 42,
    minHeight: 42,
    paddingHorizontal: 0,
    paddingVertical: 0,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#07101d',
    shadowOpacity: 0.22,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 6,
  },
  sendButtonIdle: {
    backgroundColor: '#22334f',
  },
  sendButtonStop: {
    backgroundColor: '#8e5f67',
  },
  sendButtonInterrupt: {
    backgroundColor: '#8ee5ff',
  },
  sendButtonText: {
    color: '#082033',
    fontWeight: '800',
    fontSize: 20,
    lineHeight: 20,
  },
  sendButtonTextIdle: {
    color: '#6f89ad',
  },
  referenceMovedCard: {
    borderRadius: 0,
    backgroundColor: '#101c34',
    borderWidth: 1,
    borderColor: '#23365a',
    padding: 16,
    gap: 14,
  },
  referenceMovedCopy: {
    gap: 6,
  },
  referenceMovedTitle: {
    color: '#f7fbff',
    fontSize: 16,
    fontWeight: '800',
  },
  referenceMovedText: {
    color: '#a7bbdb',
    lineHeight: 20,
  },
  referenceMovedButton: {
    alignSelf: 'flex-start',
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: '#d9ff72',
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  referenceMovedButtonText: {
    color: '#0a1831',
    fontWeight: '800',
  },
  sidebarContentScroll: {
    flex: 1,
  },
  sidebarSurfaceCard: {
    gap: 14,
  },
  sidebarSurfaceActionRow: {
    flexDirection: 'row',
    gap: 10,
    flexWrap: 'wrap',
  },
  foldSection: {
    borderRadius: 0,
    backgroundColor: '#0f172e',
    borderWidth: 1,
    borderColor: '#1d2946',
    overflow: 'hidden',
  },
  foldSectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    paddingHorizontal: 18,
    paddingVertical: 16,
    alignItems: 'center',
  },
  foldSectionHeaderCopy: {
    flex: 1,
    gap: 4,
  },
  foldSectionTitle: {
    color: '#ffffff',
    fontSize: 17,
    fontWeight: '800',
  },
  foldSectionSummary: {
    color: '#a6b9d8',
    lineHeight: 19,
  },
  foldSectionToggle: {
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: '#17253f',
    width: 34,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
  },
  foldSectionToggleText: {
    color: '#dbe7fb',
    fontWeight: '900',
    fontSize: 22,
    lineHeight: 26,
  },
  foldSectionBody: {
    paddingHorizontal: 18,
    paddingBottom: 18,
    gap: 12,
  },
  referencePanel: {
    gap: 14,
  },
  referencePanelHeader: {
    borderBottomWidth: 1,
    borderBottomColor: '#1d2946',
    paddingBottom: 12,
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  referencePanelHeaderCopy: {
    flex: 1,
    gap: 4,
  },
  referencePanelTitle: {
    color: '#f7fbff',
    fontSize: 18,
    fontWeight: '900',
  },
  referencePanelSummary: {
    color: '#8fa5c7',
    fontSize: 12,
    lineHeight: 17,
  },
  referencePanelCloseButton: {
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: '#17253f',
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  referencePanelCloseText: {
    color: '#dbe7fb',
    fontWeight: '900',
    fontSize: 12,
  },
  referenceStack: {
    gap: 12,
  },
  referenceCard: {
    borderRadius: 0,
    backgroundColor: '#15203d',
    borderWidth: 1,
    borderColor: '#263a5f',
    padding: 14,
    gap: 10,
  },
  referenceCardHeader: {
    gap: 5,
  },
  referenceCardEyebrow: {
    color: '#7ea3d8',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.9,
    textTransform: 'uppercase',
  },
  referenceCardTitle: {
    color: '#f5fbff',
    fontSize: 16,
    fontWeight: '800',
  },
  referenceCardSummary: {
    color: '#a9bcda',
    lineHeight: 19,
  },
  referenceCardMeta: {
    color: '#86a0c7',
    fontSize: 11,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  referenceCardBody: {
    color: '#e9f2ff',
    fontSize: 13,
    lineHeight: 20,
  },
  artifactPanelStack: {
    gap: 12,
  },
  artifactListScroll: {
    maxHeight: 260,
  },
  artifactList: {
    gap: 8,
  },
  artifactRow: {
    borderRadius: 14,
    backgroundColor: '#121d35',
    borderWidth: 1,
    borderColor: '#223453',
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 4,
  },
  artifactRowActive: {
    borderColor: '#7aa4ff',
    backgroundColor: '#162440',
  },
  artifactRowTitle: {
    color: '#eef4ff',
    fontSize: 13,
    fontWeight: '800',
  },
  artifactRowMeta: {
    color: '#89a2c7',
    fontSize: 11,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  artifactRowPreview: {
    color: '#c6d5ed',
    fontSize: 12,
    lineHeight: 18,
  },
  artifactPreviewCard: {
    borderRadius: 18,
    backgroundColor: '#0f182d',
    borderWidth: 1,
    borderColor: '#223453',
    padding: 14,
    gap: 12,
    minHeight: 220,
  },
  artifactPreviewHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 10,
  },
  artifactPreviewHeaderCopy: {
    flex: 1,
    gap: 4,
  },
  artifactPreviewTitle: {
    color: '#f7fbff',
    fontSize: 15,
    fontWeight: '900',
  },
  artifactPreviewMeta: {
    color: '#8fa5c7',
    fontSize: 11,
    lineHeight: 16,
  },
  artifactPreviewActions: {
    flexDirection: 'row',
    gap: 8,
  },
  artifactPreviewImage: {
    width: '100%',
    minHeight: 240,
    maxHeight: 420,
    borderRadius: 14,
    backgroundColor: '#081121',
  },
  artifactPreviewScroll: {
    maxHeight: 420,
  },
  artifactPreviewText: {
    color: '#dbe7fb',
    fontSize: 12,
    lineHeight: 19,
  },
  activityItemAccent: {
    borderWidth: 1,
    borderColor: '#3dbce4',
  },
  activityItemWarn: {
    borderWidth: 1,
    borderColor: '#d59c47',
  },
  activityItemError: {
    borderWidth: 1,
    borderColor: '#d26779',
  },
  emptyCard: {
    borderRadius: 0,
    backgroundColor: '#121c31',
    padding: 14,
    gap: 6,
  },
  emptyConversationCard: {
    borderRadius: 0,
    backgroundColor: '#131f37',
    padding: 16,
    gap: 6,
    alignItems: 'flex-start',
  },
  emptyConversationDraftCard: {
    minHeight: 180,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'stretch',
    gap: 14,
    backgroundColor: 'transparent',
  },
  emptyDraftPrompt: {
    color: '#f7fbff',
    fontSize: 22,
    fontWeight: '700',
    textAlign: 'center',
  },
  emptyDraftFolderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: '#111b31',
    borderWidth: 1,
    borderColor: '#223659',
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  emptyDraftFolderIcon: {
    color: '#8ea8d2',
    fontSize: 14,
    fontWeight: '700',
  },
  emptyDraftFolderText: {
    color: '#dce9ff',
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  emptyDraftSupportingText: {
    textAlign: 'center',
  },
  emptyFolderActionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 10,
    marginTop: 2,
  },
  emptyFolderActionButton: {
    minWidth: 150,
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: '#1d3761',
    borderWidth: 1,
    borderColor: '#34588b',
    paddingHorizontal: 15,
    paddingVertical: 10,
    alignItems: 'center',
  },
  emptyFolderActionButtonSecondary: {
    backgroundColor: '#111b31',
    borderColor: '#223659',
  },
  emptyFolderActionButtonDisabled: {
    opacity: 0.6,
  },
  emptyFolderActionButtonText: {
    color: '#f7fbff',
    fontSize: 13,
    fontWeight: '800',
  },
  emptyFolderActionButtonTextSecondary: {
    color: '#dce9ff',
  },
  emptyTitle: {
    color: '#f7fbff',
    fontWeight: '800',
  },
  emptyText: {
    color: '#a2b7d9',
    lineHeight: 20,
  },
});
