import { Platform, StyleSheet } from 'react-native';

import { DESKTOP_RECT_BUTTON_RADIUS } from './desktopUiTokens';
import { COMPOSER_LINE_HEIGHT, COMPOSER_MAX_HEIGHT, COMPOSER_MIN_HEIGHT, HUD } from './DesktopConversationView.styleConstants';

export const desktopConversationStylesPart2 = StyleSheet.create({
  sidebarSectionMeta: {
    color: '#8aa2c8',
    fontSize: 11,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  pinnedShortcutCard: {
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: '#081827',
    borderWidth: 1,
    borderColor: 'rgba(24, 243, 255, 0.14)',
    padding: 12,
    gap: 4,
  },
  pinnedShortcutLabel: {
    color: '#7ea3d8',
    fontSize: 10,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 0.9,
  },
  pinnedShortcutTitle: {
    color: '#f4f8ff',
    fontSize: 14,
    fontWeight: '900',
  },
  pinnedShortcutMeta: {
    color: '#97adcf',
    fontSize: 12,
    lineHeight: 17,
  },
  sidebarProjectsSection: {
    gap: 7,
  },
  sidebarLoadingCard: {
    minHeight: 56,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: '#111b31',
    borderWidth: 1,
    borderColor: '#223659',
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  sidebarLoadingText: {
    color: '#b9cbea',
    fontSize: 12,
    fontWeight: '700',
  },
  sidebarProjectsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 10,
  },
  projectCard: {
    borderRadius: 0,
    backgroundColor: 'transparent',
    borderWidth: 0,
    borderColor: 'transparent',
    overflow: 'visible',
  },
  projectCardSelected: {
    backgroundColor: 'transparent',
  },
  projectHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 6,
    paddingVertical: 2,
  },
  projectHeaderMain: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  projectFolderToggle: {
    paddingVertical: 1,
    paddingRight: 2,
  },
  projectFolderToggleIcon: {
    color: '#d2dae6',
    fontSize: 15,
    fontWeight: '500',
  },
  projectTitle: {
    color: '#f5f5f5',
    fontSize: 13,
    fontWeight: '700',
  },
  projectMeta: {
    color: '#7f7f7f',
    fontSize: 11,
    lineHeight: 15,
  },
  projectHeaderActions: {
    flexDirection: 'row',
    gap: 6,
    justifyContent: 'flex-end',
  },
  projectHeaderActionButton: {
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: 'transparent',
    minWidth: 26,
    minHeight: 24,
    paddingHorizontal: 5,
    paddingVertical: 3,
    alignItems: 'center',
    justifyContent: 'center',
  },
  projectHeaderActionText: {
    color: '#8ea0bd',
    fontSize: 14,
    fontWeight: '500',
  },
  projectActionIconActive: {
    color: '#dfe8f5',
  },
  projectMenu: {
    alignSelf: 'flex-end',
    minWidth: 144,
    backgroundColor: '#2d2d2d',
    borderRadius: 12,
    paddingVertical: 4,
    marginBottom: 4,
  },
  projectMenuItem: {
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  projectMenuItemText: {
    color: '#f0f0f0',
    fontSize: 12,
    fontWeight: '600',
  },
  projectMenuItemTextWarn: {
    color: '#ffb8b8',
  },
  projectContent: {
    borderTopWidth: 0,
    borderTopColor: 'transparent',
    paddingLeft: 20,
    paddingRight: 0,
    paddingTop: 1,
    paddingBottom: 2,
    gap: 2,
  },
  projectChatRow: {
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: 'transparent',
    paddingLeft: 6,
    paddingRight: 3,
    paddingVertical: 3,
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
  },
  projectChatRowDraft: {
    backgroundColor: 'transparent',
  },
  projectChatRowActive: {
    backgroundColor: '#071f32',
    borderWidth: 1,
    borderColor: HUD.cyanDim,
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
  },
  searchJumpHighlight: {
    backgroundColor: '#213254',
  },
  projectChatCopy: {
    flex: 1,
    gap: 2,
  },
  projectChatPrimary: {
    flex: 1,
    gap: 2,
  },
  projectChatTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  projectChatTitle: {
    flex: 1,
    color: '#f0f0f0',
    fontSize: 12,
    fontWeight: '500',
  },
  projectChatAge: {
    color: '#8b8b8b',
    fontSize: 10,
    fontWeight: '700',
  },
  projectChatMeta: {
    color: '#7f7f7f',
    fontSize: 10,
    lineHeight: 13,
  },
  projectChatPreview: {
    color: '#8f8f8f',
    fontSize: 10,
    lineHeight: 13,
  },
  projectChatActions: {
    alignItems: 'flex-end',
    gap: 6,
  },
  projectChatMenu: {
    alignSelf: 'flex-end',
    minWidth: 136,
    backgroundColor: '#2d2d2d',
    borderRadius: 12,
    paddingVertical: 6,
    marginRight: 4,
    marginBottom: 4,
  },
  projectMenuLabelRow: {
    paddingHorizontal: 12,
    paddingTop: 4,
    paddingBottom: 8,
  },
  projectMenuLabelText: {
    color: '#9f9f9f',
    fontSize: 11,
    fontWeight: '700',
  },
  projectChatBadge: {
    borderRadius: 0,
    backgroundColor: '#082438',
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  projectChatBadgeText: {
    color: '#9af3ff',
    fontSize: 10,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.7,
  },
  projectChatActionButton: {
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: 'transparent',
    minWidth: 20,
    paddingHorizontal: 4,
    paddingVertical: 2,
    alignItems: 'center',
  },
  projectChatActionText: {
    color: '#7889a6',
    fontSize: 12,
    fontWeight: '500',
  },
  projectActivityRow: {
    borderRadius: 0,
    backgroundColor: 'transparent',
    paddingHorizontal: 8,
    paddingVertical: 6,
    gap: 3,
  },
  projectActivityText: {
    color: '#b8b8b8',
    fontSize: 11,
    lineHeight: 15,
  },
  projectActivityMeta: {
    color: '#777',
    fontSize: 10,
    textTransform: 'uppercase',
    letterSpacing: 0.7,
  },
  projectEmptyState: {
    borderRadius: 0,
    backgroundColor: 'transparent',
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  projectEmptyText: {
    color: '#8b8b8b',
    fontSize: 10,
    lineHeight: 13,
  },
  sidebarSecondaryToggleRow: {
    flexDirection: 'row',
    gap: 10,
    flexWrap: 'wrap',
  },
  sidebarSecondaryToggle: {
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: '#16243d',
    borderWidth: 1,
    borderColor: '#22385f',
    paddingHorizontal: 12,
    paddingVertical: 10,
    minWidth: 88,
    alignItems: 'center',
  },
  sidebarSecondaryToggleActive: {
    backgroundColor: '#1d3454',
    borderColor: '#62d2ff',
  },
  sidebarSecondaryToggleDisabled: {
    opacity: 0.55,
  },
  sidebarSecondaryToggleText: {
    color: '#edf5ff',
    fontSize: 12,
    fontWeight: '900',
  },
  sessionList: {
    flex: 1,
  },
  sessionListContent: {
    gap: 12,
    paddingBottom: 6,
  },
  sessionCard: {
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: '#081827',
    borderWidth: 1,
    borderColor: 'rgba(24, 243, 255, 0.12)',
    padding: 14,
    gap: 6,
  },
  sessionCardActive: {
    backgroundColor: '#082234',
    borderColor: HUD.cyan,
  },
  sessionCardTitle: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '700',
  },
  sessionCardMeta: {
    color: '#8ea5cb',
    fontSize: 12,
  },
  sessionCardPreview: {
    color: '#dbe7fb',
    fontSize: 13,
    lineHeight: 18,
  },
  channelRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 2,
  },
  channelBadge: {
    borderRadius: 999,
    backgroundColor: '#213556',
    paddingHorizontal: 9,
    paddingVertical: 4,
  },
  channelBadgeText: {
    color: '#9fd7ff',
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  conversationColumn: {
    flex: 1,
    gap: 14,
  },
  conversationColumnDraftStage: {
    justifyContent: 'center',
    gap: 18,
  },
  surfaceModeTabsRow: {
    alignItems: 'center',
  },
  surfaceModeTabs: {
    alignSelf: 'center',
    flexDirection: 'row',
    gap: 6,
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: '#071322',
    borderWidth: 1,
    borderColor: 'rgba(24, 243, 255, 0.18)',
    padding: 4,
  },
  surfaceModeTab: {
    minWidth: 112,
    minHeight: 34,
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
    paddingVertical: 8,
  },
  surfaceModeTabHovered: {
    backgroundColor: '#0a2033',
  },
  surfaceModeTabActive: {
    backgroundColor: HUD.cyan,
  },
  surfaceModeTabText: {
    color: '#9fb3d0',
    fontSize: 13,
    fontWeight: '800',
  },
  surfaceModeTabTextActive: {
    color: '#03111d',
  },
  jarvisStage: {
    flex: 1,
    minHeight: 560,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 0,
    paddingVertical: 0,
    borderRadius: 0,
    backgroundColor: 'transparent',
    borderWidth: 0,
    borderColor: 'transparent',
    overflow: 'visible',
    position: 'relative',
    shadowColor: HUD.cyan,
    shadowOpacity: 0,
    shadowRadius: 0,
    shadowOffset: { width: 0, height: 0 },
  },
  jarvisDashboard: {
    width: '100%',
    maxWidth: 1180,
    minHeight: 610,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 14,
    flexWrap: 'nowrap',
  },
  jarvisPeripheralRail: {
    width: 218,
    minHeight: 480,
    justifyContent: 'center',
    gap: 10,
  },
  jarvisCenterStack: {
    width: 500,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  jarvisCoreModule: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  jarvisCoreFrame: {
    width: '100%',
    maxWidth: 500,
    minHeight: 405,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    backgroundColor: HUD.panel,
    borderWidth: 1,
    borderColor: HUD.edge,
    overflow: 'hidden',
    position: 'relative',
    shadowColor: HUD.cyan,
    shadowOpacity: 0.08,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 0 },
  },
  jarvisSideStack: {
    flexGrow: 1.12,
    flexShrink: 1,
    minWidth: 460,
    maxWidth: 610,
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'stretch',
    alignContent: 'center',
    gap: 14,
  },
  jarvisModule: {
    borderRadius: 10,
    backgroundColor: 'rgba(4, 18, 32, 0.76)',
    borderWidth: 1,
    borderColor: 'rgba(24, 243, 255, 0.24)',
    paddingHorizontal: 11,
    paddingVertical: 10,
    gap: 7,
    ...(Platform.OS === 'web'
      ? ({
          boxShadow: 'inset 0 0 0 1px rgba(24, 243, 255, 0.035)',
        } as any)
      : null),
  },
  jarvisOutputModule: {
    width: '100%',
    minHeight: 78,
  },
  jarvisToolOutputHovered: {
    borderColor: 'rgba(24, 243, 255, 0.46)',
    backgroundColor: 'rgba(5, 25, 43, 0.9)',
  },
  jarvisToolHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  jarvisToolHeaderCopy: {
    flex: 1,
    gap: 4,
  },
  jarvisToolSummary: {
    color: '#edf7ff',
    fontSize: 12,
    fontWeight: '800',
    lineHeight: 16,
  },
  jarvisToolToggle: {
    minWidth: 50,
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    borderWidth: 1,
    borderColor: 'rgba(24, 243, 255, 0.26)',
    color: '#8fefff',
    fontSize: 11,
    fontWeight: '900',
    textAlign: 'center',
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  jarvisControlGrid: {
    flexBasis: '100%',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  jarvisControlTile: {
    width: '100%',
    minHeight: 92,
    justifyContent: 'space-between',
  },
  jarvisTalkButton: {
    minHeight: 146,
    borderColor: 'rgba(24, 243, 255, 0.34)',
    backgroundColor: 'rgba(4, 23, 39, 0.9)',
  },
  jarvisTalkButtonHovered: {
    borderColor: HUD.cyan,
    backgroundColor: 'rgba(5, 35, 55, 0.95)',
  },
  jarvisTalkButtonPressed: {
    backgroundColor: 'rgba(24, 243, 255, 0.16)',
    borderColor: HUD.cyan,
  },
  jarvisTalkButtonActive: {
    backgroundColor: 'rgba(24, 243, 255, 0.14)',
    borderColor: HUD.cyan,
    shadowColor: HUD.cyan,
    shadowOpacity: 0.18,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 0 },
  },
  jarvisTalkButtonSelected: {
    backgroundColor: 'rgba(24, 243, 255, 0.1)',
    borderColor: 'rgba(24, 243, 255, 0.58)',
  },
  jarvisPttToggleRow: {
    width: '100%',
    minHeight: 44,
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    borderWidth: 1,
    borderColor: 'rgba(24, 243, 255, 0.24)',
    backgroundColor: 'rgba(5, 20, 34, 0.9)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
    paddingVertical: 7,
    gap: 10,
  },
  jarvisPttToggleRowHovered: {
    borderColor: HUD.cyan,
    backgroundColor: 'rgba(6, 31, 50, 0.95)',
  },
  jarvisPttToggleCopy: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  jarvisPttSwitchTrack: {
    width: 42,
    height: 22,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(24, 243, 255, 0.2)',
    backgroundColor: 'rgba(2, 12, 21, 0.92)',
    padding: 2,
    justifyContent: 'center',
  },
  jarvisPttSwitchTrackActive: {
    borderColor: HUD.cyan,
    backgroundColor: 'rgba(24, 243, 255, 0.22)',
  },
  jarvisPttSwitchKnob: {
    width: 16,
    height: 16,
    borderRadius: 999,
    backgroundColor: '#5f7b96',
  },
  jarvisPttSwitchKnobActive: {
    backgroundColor: HUD.cyan,
    transform: [{ translateX: 18 }],
  },
  jarvisHoldModeText: {
    color: '#edf7ff',
    fontSize: 13,
    fontWeight: '900',
    lineHeight: 16,
  },
  jarvisHoldModeTextActive: {
    color: '#bdf8ff',
  },
  jarvisHoldModeDetailActive: {
    color: '#9af3ff',
  },
  jarvisHoldCaptureButton: {
    width: '100%',
    minHeight: 40,
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    borderWidth: 1,
    borderColor: 'rgba(24, 243, 255, 0.28)',
    backgroundColor: 'rgba(2, 13, 24, 0.74)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  jarvisHoldCaptureButtonHovered: {
    borderColor: HUD.cyan,
    backgroundColor: 'rgba(6, 32, 50, 0.9)',
  },
  jarvisHoldCaptureButtonPressed: {
    borderColor: HUD.cyan,
    backgroundColor: 'rgba(24, 243, 255, 0.15)',
  },
  jarvisHoldCaptureButtonActive: {
    borderColor: HUD.cyan,
    backgroundColor: 'rgba(24, 243, 255, 0.2)',
  },
  jarvisHoldCaptureButtonDisabled: {
    opacity: 0.5,
  },
  jarvisHoldCaptureText: {
    color: '#f7fbff',
    fontSize: 13,
    fontWeight: '900',
    lineHeight: 16,
  },
  jarvisHoldCaptureDetail: {
    color: '#8fefff',
    fontSize: 10,
    fontWeight: '900',
    lineHeight: 13,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  jarvisTalkButtonDisabled: {
    opacity: 0.52,
  },
  jarvisTalkButtonValue: {
    color: '#f7fbff',
    fontSize: 16,
    fontWeight: '900',
    lineHeight: 20,
  },
  jarvisTalkButtonDetail: {
    color: '#8fefff',
    fontSize: 11,
    fontWeight: '800',
    lineHeight: 15,
  },
  jarvisShortcutHint: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    borderWidth: 1,
    borderColor: 'rgba(24, 243, 255, 0.18)',
    backgroundColor: 'rgba(2, 13, 24, 0.72)',
    paddingHorizontal: 7,
    paddingVertical: 4,
  },
  jarvisShortcutHintText: {
    color: '#7199b8',
    fontSize: 9,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  jarvisShortcutKey: {
    color: '#071827',
    fontSize: 10,
    fontWeight: '900',
    borderRadius: 4,
    overflow: 'hidden',
    backgroundColor: HUD.cyan,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  jarvisContextTile: {
    minHeight: 142,
  },
  jarvisContextMeterTrack: {
    height: 8,
    borderRadius: 999,
    backgroundColor: 'rgba(32, 62, 92, 0.78)',
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(24, 243, 255, 0.13)',
  },
  jarvisContextMeterFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: HUD.cyan,
  },
  jarvisContextMeterFillWarn: {
    backgroundColor: HUD.amber,
  },
  jarvisContextMeterFillCompact: {
    backgroundColor: '#82ffb3',
  },
  jarvisContextMeta: {
    color: '#8daed3',
    fontSize: 10,
    fontWeight: '800',
    lineHeight: 14,
  },
  jarvisBottomRail: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 9,
  },
  jarvisVoiceOutputModule: {
    flex: 1,
    minHeight: 62,
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: 10,
    paddingVertical: 8,
  },
  jarvisVoiceOutputColumn: {
    flex: 1,
    minWidth: 0,
    gap: 5,
  },
  jarvisVoiceOutputDivider: {
    width: 1,
    alignSelf: 'stretch',
    backgroundColor: 'rgba(24, 243, 255, 0.16)',
  },
  jarvisVoiceOutputText: {
    color: '#edf7ff',
    fontSize: 12,
    fontWeight: '800',
    lineHeight: 17,
  },
  jarvisTileHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  jarvisTileSignal: {
    color: 'rgba(24, 243, 255, 0.38)',
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0.6,
  },
  jarvisVoiceEngineModule: {
    width: '100%',
    minHeight: 148,
    justifyContent: 'space-between',
  },
  jarvisLogModule: {
    width: '100%',
    maxHeight: 220,
  },
  jarvisModuleLabel: {
    color: '#63e8ff',
    fontSize: 10,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 1.1,
  },
  jarvisHudBackdrop: {
    ...StyleSheet.absoluteFillObject,
    opacity: 0.72,
    ...(Platform.OS === 'web'
      ? ({
          backgroundImage: [
            'radial-gradient(circle at 38% 48%, rgba(24, 243, 255, 0.11) 0, rgba(24, 243, 255, 0.035) 31%, transparent 56%)',
            'linear-gradient(rgba(24, 243, 255, 0.032) 1px, transparent 1px)',
            'linear-gradient(90deg, rgba(24, 243, 255, 0.028) 1px, transparent 1px)',
          ].join(', '),
          backgroundSize: '100% 100%, 32px 32px, 32px 32px',
        } as any)
      : null),
  },
  jarvisScanline: {
    position: 'absolute',
    left: '8%',
    right: '8%',
    top: '49.5%',
    height: 1,
    backgroundColor: 'rgba(24, 243, 255, 0.2)',
  },
  jarvisCorner: {
    position: 'absolute',
    width: 86,
    height: 86,
    borderColor: HUD.cyan,
    opacity: 0.52,
  },
  jarvisCornerTopLeft: {
    top: 16,
    left: 16,
    borderTopWidth: 1,
    borderLeftWidth: 1,
  },
  jarvisCornerTopRight: {
    top: 16,
    right: 16,
    borderTopWidth: 1,
    borderRightWidth: 1,
  },
  jarvisCornerBottomLeft: {
    bottom: 16,
    left: 16,
    borderBottomWidth: 1,
    borderLeftWidth: 1,
  },
  jarvisCornerBottomRight: {
    bottom: 16,
    right: 16,
    borderBottomWidth: 1,
    borderRightWidth: 1,
  },
  jarvisOrbWrap: {
    width: 386,
    height: 386,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  jarvisOuterRing: {
    position: 'absolute',
    width: 366,
    height: 366,
    borderRadius: 183,
    borderWidth: 1,
    borderColor: 'rgba(24, 243, 255, 0.3)',
    backgroundColor: 'rgba(10, 105, 204, 0.025)',
  },
  jarvisFineRing: {
    position: 'absolute',
    width: 328,
    height: 328,
    borderRadius: 164,
    borderWidth: 1,
    borderColor: 'rgba(24, 243, 255, 0.16)',
  },
  jarvisTickRing: {
    position: 'absolute',
    width: 350,
    height: 350,
    borderRadius: 175,
  },
  jarvisTickRay: {
    position: 'absolute',
    width: 350,
    height: 350,
    left: 0,
    top: 0,
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingTop: 3,
  },
  jarvisTick: {
    width: 1,
    height: 7,
    borderRadius: 1,
    backgroundColor: 'rgba(24, 243, 255, 0.38)',
  },
  jarvisTickMajor: {
    width: 2,
    height: 15,
    backgroundColor: 'rgba(24, 243, 255, 0.74)',
  },
  jarvisReticleHorizontal: {
    position: 'absolute',
    width: 330,
    height: 1,
    backgroundColor: 'rgba(24, 243, 255, 0.17)',
  },
  jarvisReticleVertical: {
    position: 'absolute',
    width: 1,
    height: 330,
    backgroundColor: 'rgba(24, 243, 255, 0.14)',
  },
  jarvisOrbPulse: {
    position: 'absolute',
    width: 272,
    height: 272,
    borderRadius: 136,
    borderWidth: 1,
    borderColor: 'rgba(24, 243, 255, 0.5)',
    backgroundColor: 'rgba(24, 243, 255, 0.045)',
  },
  jarvisOrb: {
    width: 210,
    height: 210,
    borderRadius: 105,
    backgroundColor: '#06182a',
    borderWidth: 1,
    borderColor: 'rgba(75, 200, 255, 0.74)',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: HUD.cyan,
    shadowOpacity: 0.2,
    shadowRadius: 26,
    shadowOffset: { width: 0, height: 0 },
    ...(Platform.OS === 'web'
      ? ({
          backgroundImage: 'radial-gradient(circle at 50% 50%, rgba(24, 243, 255, 0.18) 0%, rgba(6, 24, 42, 0.98) 58%, rgba(3, 11, 20, 0.98) 100%)',
        } as any)
      : null),
  },
  jarvisOrbListening: {
    borderColor: HUD.cyan,
    backgroundColor: '#062337',
  },
  jarvisOrbWorking: {
    borderColor: '#6dd8ff',
    backgroundColor: '#071f38',
  },
  jarvisOrbMuted: {
    borderColor: '#526276',
    backgroundColor: '#111923',
    shadowOpacity: 0.06,
  },
  jarvisOrbError: {
    borderColor: HUD.magenta,
    backgroundColor: '#2b1420',
    shadowColor: HUD.magenta,
  },
  jarvisOrbRingA: {
    position: 'absolute',
    width: 176,
    height: 176,
    borderRadius: 88,
    borderWidth: 1,
    borderColor: 'rgba(24, 243, 255, 0.18)',
  },
  jarvisOrbRingB: {
    position: 'absolute',
    width: 136,
    height: 136,
    borderRadius: 68,
    borderWidth: 1,
    borderColor: 'rgba(24, 243, 255, 0.24)',
  },
  jarvisOrbRingC: {
    position: 'absolute',
    width: 82,
    height: 82,
    borderRadius: 41,
    borderWidth: 1,
    borderColor: 'rgba(24, 243, 255, 0.2)',
  },
  jarvisOrbCore: {
    width: 118,
    height: 72,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
  },
  jarvisWaveBar: {
    width: 4,
    borderRadius: 999,
    backgroundColor: HUD.cyan,
    shadowColor: HUD.cyan,
    shadowOpacity: 0.18,
    shadowRadius: 5,
    shadowOffset: { width: 0, height: 0 },
  },
  jarvisMuteButton: {
    minWidth: 112,
    minHeight: 34,
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: '#061827',
    borderWidth: 1,
    borderColor: 'rgba(24, 243, 255, 0.28)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
    paddingVertical: 7,
  },
  jarvisMuteButtonHovered: {
    borderColor: HUD.cyan,
    backgroundColor: '#082235',
  },
  jarvisMuteButtonActive: {
    backgroundColor: 'rgba(255, 44, 114, 0.16)',
    borderColor: HUD.magenta,
  },
  jarvisMuteButtonText: {
    color: '#d8e7ff',
    fontSize: 13,
    fontWeight: '900',
  },
  jarvisMuteButtonTextActive: {
    color: '#ffb8cb',
  },
  jarvisStatusCopy: {
    alignItems: 'center',
    gap: 7,
    paddingHorizontal: 24,
  },
  jarvisPhase: {
    color: '#f7fbff',
    fontSize: 23,
    fontWeight: '900',
    letterSpacing: 0,
  },
  jarvisDetail: {
    color: '#8fefff',
    fontSize: 13,
    fontWeight: '700',
    textAlign: 'center',
  },
  jarvisActionRow: {
    flexDirection: 'row',
    gap: 10,
  },
  jarvisActionButton: {
    flex: 1,
    minHeight: 42,
    borderRadius: 10,
    backgroundColor: 'rgba(7, 24, 42, 0.92)',
    borderWidth: 1,
    borderColor: 'rgba(24, 243, 255, 0.24)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  jarvisActionButtonHovered: {
    borderColor: HUD.cyan,
    backgroundColor: '#082235',
  },
  jarvisActionButtonActive: {
    backgroundColor: HUD.cyan,
    borderColor: HUD.cyan,
  },
  jarvisActionText: {
    color: '#d8e7ff',
    fontSize: 13,
    fontWeight: '800',
  },
  jarvisActionTextActive: {
    color: '#03111d',
  },
  jarvisDrawer: {
    width: '82%',
    maxWidth: 720,
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: HUD.panelGlass,
    borderWidth: 1,
    borderColor: HUD.edge,
    padding: 14,
    gap: 12,
    shadowColor: HUD.cyan,
    shadowOpacity: 0.08,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 0 },
  },
  jarvisDrawerMetricRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  jarvisDrawerMetric: {
    flex: 1,
    minWidth: 160,
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: 'rgba(8, 28, 47, 0.86)',
    borderWidth: 1,
    borderColor: 'rgba(24, 243, 255, 0.12)',
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 4,
  },
  jarvisDrawerLabel: {
    color: '#74e9ff',
    fontSize: 10,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  jarvisDrawerValue: {
    color: '#eef6ff',
    fontSize: 12,
    fontWeight: '800',
    lineHeight: 17,
  },
  jarvisTtsSwitch: {
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: 'rgba(8, 28, 47, 0.72)',
    borderWidth: 1,
    borderColor: 'rgba(24, 243, 255, 0.12)',
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 10,
  },
  jarvisTtsSwitchCopy: {
    gap: 3,
    flexShrink: 1,
    minWidth: 150,
  },
  jarvisTtsSwitchButtons: {
    flexDirection: 'row',
    gap: 7,
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
  },
  jarvisTtsSwitchButton: {
    minHeight: 31,
    flexGrow: 1,
    minWidth: 86,
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    borderWidth: 1,
    borderColor: HUD.cyanDim,
    backgroundColor: '#061827',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  jarvisTtsSwitchButtonHovered: {
    borderColor: HUD.cyan,
  },
  jarvisTtsSwitchButtonActive: {
    backgroundColor: HUD.cyan,
    borderColor: HUD.cyan,
  },
  jarvisTtsSwitchButtonDisabled: {
    opacity: 0.55,
  },
  jarvisTtsSwitchButtonText: {
    color: '#d8e7ff',
    fontSize: 12,
    fontWeight: '800',
  },
  jarvisTtsSwitchButtonTextActive: {
    color: '#03111d',
  },
  jarvisDrawerNotice: {
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: 'rgba(10, 36, 61, 0.82)',
    borderWidth: 1,
    borderColor: 'rgba(255, 184, 107, 0.24)',
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 3,
  },
  jarvisDrawerNoticeText: {
    color: '#e5eefc',
    fontSize: 12,
    lineHeight: 18,
  },
  jarvisActivityList: {
    gap: 6,
  },
  jarvisActivityItem: {
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: 'rgba(8, 25, 42, 0.82)',
    borderWidth: 1,
    borderColor: 'rgba(24, 243, 255, 0.13)',
    borderLeftWidth: 2,
    borderLeftColor: 'rgba(24, 243, 255, 0.22)',
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  jarvisActivityItemAccent: {
    backgroundColor: 'rgba(9, 39, 58, 0.88)',
    borderLeftColor: HUD.cyan,
  },
  jarvisActivityItemWarn: {
    backgroundColor: '#2a2314',
    borderLeftColor: HUD.amber,
  },
  jarvisActivityItemError: {
    backgroundColor: '#321821',
    borderLeftColor: HUD.magenta,
  },
  jarvisActivityText: {
    color: '#d7e3f7',
    fontSize: 12,
    lineHeight: 17,
  },
  jarvisDrawerEmpty: {
    color: '#8fa5c7',
    fontSize: 12,
  },
  compactHeader: {
    borderRadius: 22,
    backgroundColor: '#0d172b',
    borderWidth: 1,
    borderColor: '#1f304f',
    paddingHorizontal: 18,
    paddingVertical: 14,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 14,
  },
  compactHeaderCopy: {
    flex: 1,
    gap: 4,
  },
  compactTitle: {
    color: '#f7fbff',
    fontSize: 18,
    fontWeight: '800',
  },
  compactSubtitle: {
    color: '#8ea8d2',
    fontSize: 12,
  },
  agentStatusBar: {
    borderRadius: 18,
    backgroundColor: '#081225',
    borderWidth: 1,
    borderColor: '#1d2b49',
    paddingHorizontal: 14,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flexWrap: 'wrap',
  },
  agentStatusItem: {
    minWidth: 138,
    borderRadius: 14,
    backgroundColor: '#101d35',
    paddingHorizontal: 12,
    paddingVertical: 9,
    gap: 3,
  },
  agentStatusMeter: {
    flex: 1,
    minWidth: 220,
    borderRadius: 14,
    backgroundColor: '#101d35',
    paddingHorizontal: 12,
    paddingVertical: 9,
    gap: 7,
  },
  agentStatusMeterHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  agentStatusLabel: {
    color: '#7f96bc',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.9,
    textTransform: 'uppercase',
  },
  agentStatusValue: {
    color: '#f7fbff',
    fontSize: 13,
    fontWeight: '900',
  },
  contextStateBadge: {
    borderRadius: 0,
    paddingHorizontal: 10,
    paddingVertical: 4,
    alignSelf: 'flex-start',
  },
  contextStateBadgeNeutral: {
    backgroundColor: '#1c2b47',
  },
  contextStateBadgeWarn: {
    backgroundColor: '#5c3e00',
  },
  contextStateBadgeCompact: {
    backgroundColor: '#103824',
  },
  contextStateBadgeText: {
    color: '#f7fbff',
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  contextMeterTrack: {
    height: 7,
    borderRadius: 999,
    backgroundColor: '#1c2b47',
    overflow: 'hidden',
  },
  contextMeterFill: {
    height: 7,
    borderRadius: 999,
    backgroundColor: '#62d2ff',
  },
  contextMeterFillWarn: {
    backgroundColor: '#ffbf3c',
  },
  contextMeterFillCompact: {
    backgroundColor: '#7be495',
  },
  contextMeterFootnote: {
    color: '#9bb0d4',
    fontSize: 10,
    fontWeight: '800',
    alignSelf: 'flex-end',
  },
  taskBoardCard: {
    borderRadius: 0,
    backgroundColor: '#0b1730',
    borderWidth: 1,
    borderColor: '#21406d',
    paddingHorizontal: 16,
    paddingVertical: 14,
    gap: 12,
  },
  taskBoardCardWarn: {
    borderColor: '#76511b',
    backgroundColor: '#1f1405',
  },
  taskBoardCardComplete: {
    borderColor: '#1f5f42',
    backgroundColor: '#0d2017',
  },
  taskBoardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
  },
  taskBoardHeaderCopy: {
    flex: 1,
    gap: 4,
  },
  taskBoardHeaderActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
  },
  taskBoardEyebrow: {
    color: '#8cb9ff',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  taskBoardGoal: {
    color: '#f7fbff',
    fontSize: 15,
    fontWeight: '900',
  },
  taskBoardMeta: {
    color: '#9eb7dd',
    fontSize: 12,
    lineHeight: 18,
  },
  taskBoardBadge: {
    borderRadius: 0,
    backgroundColor: '#17345e',
    paddingHorizontal: 11,
    paddingVertical: 6,
  },
  taskBoardBadgeWarn: {
    backgroundColor: '#825c1b',
  },
  taskBoardBadgeComplete: {
    backgroundColor: '#1c6a47',
  },
  taskBoardBadgeText: {
    color: '#f7fbff',
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  taskBoardToggleButton: {
    borderRadius: DESKTOP_RECT_BUTTON_RADIUS,
    backgroundColor: '#13233f',
    borderWidth: 1,
    borderColor: '#28446e',
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  taskBoardToggleButtonText: {
    color: '#dce8fb',
    fontSize: 11,
    fontWeight: '900',
  },
  taskBoardAlert: {
    borderRadius: 0,
    backgroundColor: 'rgba(255, 191, 60, 0.14)',
    borderWidth: 1,
    borderColor: 'rgba(255, 191, 60, 0.35)',
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 3,
  },
  taskBoardAlertLabel: {
    color: '#ffd37b',
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  taskBoardAlertText: {
    color: '#fce7b4',
    fontSize: 12,
    lineHeight: 18,
  },
  taskBoardInfoRow: {
    flexDirection: 'row',
    gap: 10,
    flexWrap: 'wrap',
  },
  taskBoardInfoChip: {
    flex: 1,
    minWidth: 220,
    borderRadius: 0,
    backgroundColor: '#101f3b',
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 4,
  },
  taskBoardInfoLabel: {
    color: '#7d97c1',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.7,
    textTransform: 'uppercase',
  },
  taskBoardInfoValue: {
    color: '#f7fbff',
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '700',
  },
  taskBoardSteps: {
    gap: 9,
  },
  taskBoardStepRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  taskBoardStepPrefix: {
    color: '#9fc7ff',
    fontSize: 12,
    fontWeight: '900',
    paddingTop: 1,
  },
  taskBoardStepCopy: {
    flex: 1,
    gap: 2,
  },
  taskBoardStepTitle: {
    color: '#f7fbff',
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 18,
  },
  taskBoardStepMeta: {
    color: '#9bb1d4',
    fontSize: 11,
    lineHeight: 17,
  },
  completedTaskBoardsSection: {
    gap: 12,
  },
  completedTaskBoardsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  completedTaskBoardsHeaderCopy: {
    gap: 2,
  },
});
